# SQL CARTO QUERY FUNCTION
# written for PUI2016_Python2

In [1]:
SQL_SOURCE = 'https://fl1210.carto.com/api/v2/sql?q='

import urllib2
import urllib
import StringIO
import ast
import pandas as pd

def queryCartoDB(query, format='CSV', source=SQL_SOURCE):
    '''queries carto datasets from a given carto account
    Arguments: 
    query - string: a valid sql query string
    format - outlut format  OPTIONAL (default CSV)
    source - a valid sql api endpoint OPTIONAL (default carto fb55 account)
    Returns:
    the return of the sql query AS A STRING
    NOTES:
    designed for the carto API, tested only with CSV return format'''
    
    data = urllib.urlencode({'format': format, 'q': query})
    try:
        response = urllib2.urlopen(source, data)
    except urllib2.HTTPError, e:
        raise ValueError('\n'.join(ast.literal_eval(e.readline())['error']))
    except Exception:
        raise
    return response.read()

In [2]:
test = '''
SELECT *
FROM citibike
'''

In [3]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,5960,NaN,NaN,1,1965.0,19217,462,435,351,Subscriber,W 22 St & 10 Ave,W 21 St & 6 Ave,-74.004519,40.746920,-73.994156,40.741740,2015-02-01 20:42:00+00,2015-02-01 20:36:00+00
1,9806,NaN,NaN,1,1971.0,17575,488,167,643,Subscriber,W 39 St & 9 Ave,E 39 St & 3 Ave,-73.993722,40.756458,-73.976049,40.748901,2015-02-03 14:50:00+00,2015-02-03 14:39:00+00
2,13113,NaN,NaN,1,1973.0,20313,440,332,1379,Subscriber,E 45 St & 3 Ave,Cherry St,-73.972826,40.752554,-73.979481,40.712199,2015-02-04 07:30:00+00,2015-02-04 07:07:00+00
3,1,NaN,NaN,2,1978.0,17131,423,521,801,Subscriber,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-01 00:14:00+00,2015-02-01 00:00:00+00
4,2,NaN,NaN,1,1993.0,21289,504,497,379,Subscriber,1 Ave & E 15 St,E 17 St & Broadway,-73.981656,40.732219,-73.990093,40.737050,2015-02-01 00:07:00+00,2015-02-01 00:00:00+00
5,3,NaN,NaN,2,1969.0,18903,127,281,2474,Subscriber,Barrow St & Hudson St,Grand Army Plaza & Central Park S,-74.006744,40.731724,-73.973715,40.764397,2015-02-01 00:42:00+00,2015-02-01 00:01:00+00
6,4,NaN,NaN,2,1985.0,21044,505,2004,818,Subscriber,6 Ave & W 33 St,6 Ave & Broome St,-73.988484,40.749013,-74.004704,40.724399,2015-02-01 00:15:00+00,2015-02-01 00:01:00+00
7,5,NaN,NaN,1,1957.0,19868,83,323,544,Subscriber,Atlantic Ave & Fort Greene Pl,Lawrence St & Willoughby St,-73.976323,40.683826,-73.986317,40.692362,2015-02-01 00:10:00+00,2015-02-01 00:01:00+00
8,6,NaN,NaN,1,1979.0,15854,2002,373,717,Subscriber,Wythe Ave & Metropolitan Ave,Willoughby Ave & Walworth St,-73.963198,40.716887,-73.953820,40.693317,2015-02-01 00:14:00+00,2015-02-01 00:02:00+00
9,7,NaN,NaN,1,1983.0,15173,504,352,1306,Subscriber,1 Ave & E 15 St,W 56 St & 6 Ave,-73.981656,40.732219,-73.977225,40.763406,2015-02-01 00:26:00+00,2015-02-01 00:04:00+00
10,8,NaN,NaN,1,1955.0,17862,116,439,913,Subscriber,W 17 St & 8 Ave,E 4 St & 2 Ave,-74.001497,40.741776,-73.989780,40.726281,2015-02-01 00:19:00+00,2015-02-01 00:04:00+00
11,9,NaN,NaN,2,1985.0,21183,2012,335,759,Subscriber,E 27 St & 1 Ave,Washington Pl & Broadway,-73.976806,40.739445,-73.994046,40.729039,2015-02-01 00:17:00+00,2015-02-01 00:04:00+00
12,10,NaN,NaN,1,1982.0,14843,444,284,585,Subscriber,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
13,11,NaN,NaN,2,1988.0,16936,444,284,581,Subscriber,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
14,12,NaN,NaN,2,1991.0,21507,472,498,204,Subscriber,E 32 St & Park Ave,Broadway & W 32 St,-73.981948,40.745712,-73.988084,40.748549,2015-02-01 00:08:00+00,2015-02-01 00:05:00+00
15,13,NaN,NaN,2,1982.0,17456,307,368,1169,Subscriber,Canal St & Rutgers St,Carmine St & 6 Ave,-73.989900,40.714275,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:07:00+00
16,14,NaN,NaN,2,1990.0,14679,2012,326,419,Subscriber,E 27 St & 1 Ave,E 11 St & 1 Ave,-73.976806,40.739445,-73.984267,40.729538,2015-02-01 00:14:00+00,2015-02-01 00:07:00+00
17,15,NaN,NaN,1,1977.0,18978,212,285,527,Subscriber,W 16 St & The High Line,Broadway & E 14 St,-74.006818,40.743349,-73.990741,40.734546,2015-02-01 00:17:00+00,2015-02-01 00:09:00+00
18,16,NaN,NaN,1,1968.0,16496,488,368,1013,Subscriber,W 39 St & 9 Ave,Carmine St & 6 Ave,-73.993722,40.756458,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:10:00+00
19,17,NaN,NaN,1,1990.0,17107,331,394,587,Subscriber,Pike St & Monroe St,E 9 St & Avenue C,-73.991930,40.711731,-73.977688,40.725213,2015-02-01 00:23:00+00,2015-02-01 00:13:00+00
20,18,NaN,NaN,1,1987.0,16984,507,326,525,Subscriber,E 25 St & 2 Ave,E 11 St & 1 Ave,-73.979738,40.739126,-73.984267,40.729538,2015-02-01 00:22:00+00,2015-02-01 00:13:00+00
21,19,NaN,NaN,1,1980.0,15997,305,493,670,Subscriber,E 58 St & 3 Ave,W 45 St & 6 Ave,-73.967245,40.760958,-73.982912,40.756800,2015-02-01 00:26:00+00,2015-02-01 00:14:00+00
22,20,NaN,NaN,1,1960.0,21516,223,445,711,Subscriber,W 13 St & 7 Ave,E 10 St & Avenue A,-73.999947,40.737815,-73.981420,40.727408,2015-02-01 00:27:00+00,2015-02-01 00:15:00+00
23,21,NaN,NaN,1,1986.0,15815,457,428,1559,Subscriber,Broadway & W 58 St,E 3 St & 1 Ave,-73.981693,40.766953,-73.987834,40.724677,2015-02-01 00:42:00+00,2015-02-01 00:16:00+00
24,22,NaN,NaN,1,1987.0,18727,477,228,683,Subscriber,W 41 St & 8 Ave,E 48 St & 3 Ave,-73.990026,40.756405,-73.971879,40.754601,2015-02-01 00:27:00+00,2015-02-01 00:16:00+00
25,23,NaN,NaN,1,1969.0,14982,488,513,522,Subscriber,W 39 St & 9 Ave,W 56 St & 10 Ave,-73.993722,40.756458,-73.988639,40.768254,2015-02-01 00:24:00+00,2015-02-01 00:16:00+00
26,24,NaN,NaN,1,1957.0,16391,518,507,389,Subscriber,E 39 St & 2 Ave,E 25 St & 2 Ave,-73.973442,40.747804,-73.979738,40.739126,2015-02-01 00:23:00+00,2015-02-01 00:16:00+00
27,25,NaN,NaN,1,1981.0,15947,473,439,276,Subscriber,Rivington St & Chrystie St,E 4 St & 2 Ave,-73.991925,40.721101,-73.989780,40.726281,2015-02-01 00:21:00+00,2015-02-01 00:16:00+00
28,26,NaN,NaN,1,1993.0,16917,531,128,907,Subscriber,Forsyth St & Broome St,MacDougal St & Prince St,-73.992663,40.718939,-74.002971,40.727103,2015-02-01 00:32:00+00,2015-02-01 00:17:00+00
29,27,NaN,NaN,1,1975.0,15924,528,490,946,Subscriber,2 Ave & E 31 St,8 Ave & W 33 St,-73.977061,40.742909,-73.993934,40.751551,2015-02-01 00:33:00+00,2015-02-01 00:18:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46170,46171,NaN,NaN,1,1988.0,15733,435,335,812,Subscriber,W 21 St & 6 Ave,Washington Pl & Broadway,-73.994156,40.741740,-73.994046,40.729039,2015-02-08 00:05:00+00,2015-02-07 23:51:00+00
46171,46172,NaN,NaN,1,1995.0,16931,504,361,647,Subscriber,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:51:00+00
46172,46173,NaN,NaN,1,1987.0,17202,401,152,563,Subscriber,Allen St & Rivington St,Warren St & Church St,-73.989978,40.720196,-74.009106,40.714740,2015-02-08 00:00:00+00,2015-02-07 23:51:00+00
46173,46174,NaN,NaN,2,1989.0,20314,439,483,470,Subscriber,E 4 St & 2 Ave,E 12 St & 3 Ave,-73.989780,40.726281,-73.988900,40.732233,2015-02-07 23:59:00+00,2015-02-07 23:51:00+00
46174,46175,NaN,NaN,1,1989.0,21531,395,467,299,Subscriber,Bond St & Schermerhorn St,Dean St & 4 Ave,-73.984106,40.688070,-73.978951,40.683125,2015-02-07 23:56:00+00,2015-02-07 23:51:00+00
46175,46176,NaN,NaN,1,1968.0,21491,504,361,629,Subscriber,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:52:00+00
46176,46177,NaN,NaN,1,1990.0,15367,380,402,499,Subscriber,W 4 St & 7 Ave S,Broadway & E 22 St,-74.002939,40.734011,-73.989551,40.740343,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
46177,46178,NaN,NaN,2,1973.0,18978,368,369,474,Subscriber,Carmine St & 6 Ave,Washington Pl & 6 Ave,-74.002150,40.730386,-74.000264,40.732241,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
46178,46179,NaN,NaN,1,1980.0,19507,504,476,345,Subscriber,1 Ave & E 15 St,E 31 St & 3 Ave,-73.981656,40.732219,-73.979661,40.743943,2015-02-07 23:58:00+00,2015-02-07 23:52:00+00
46179,46180,NaN,NaN,1,1980.0,16936,160,499,829,Subscriber,E 37 St & Lexington Ave,Broadway & W 60 St,-73.978311,40.748238,-73.981918,40.769155,2015-02-08 00:07:00+00,2015-02-07 23:53:00+00
46180,46181,NaN,NaN,1,1982.0,18689,531,368,776,Subscriber,Forsyth St & Broome St,Carmine St & 6 Ave,-73.992663,40.718939,-74.002150,40.730386,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
46181,46182,NaN,NaN,1,1972.0,15781,478,520,697,Subscriber,11 Ave & W 41 St,W 52 St & 5 Ave,-73.998842,40.760301,-73.976485,40.759923,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
46182,46183,NaN,NaN,1,1988.0,15081,471,467,1703,Subscriber,Grand St & Havemeyer St,Dean St & 4 Ave,-73.956981,40.712868,-73.978951,40.683125,2015-02-08 00:23:00+00,2015-02-07 23:54:00+00
46183,46184,NaN,NaN,1,1983.0,21672,247,479,922,Subscriber,Perry St & Bleecker St,9 Ave & W 45 St,-74.004831,40.735354,-73.991255,40.760193,2015-02-08 00:10:00+00,2015-02-07 23:54:00+00
46184,46185,NaN,NaN,1,1970.0,16336,488,457,849,Subscriber,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
46185,46186,NaN,NaN,1,1973.0,21609,488,457,826,Subscriber,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
46186,46187,NaN,NaN,1,1964.0,19470,3002,328,473,Subscriber,South End Ave & Liberty St,Watts St & Greenwich St,-74.015756,40.711512,-74.009660,40.724055,2015-02-08 00:02:00+00,2015-02-07 23:54:00+00
46187,46188,NaN,NaN,1,1960.0,18167,450,510,332,Subscriber,W 49 St & 8 Ave,W 51 St & 6 Ave,-73.987882,40.762272,-73.980420,40.760660,2015-02-07 23:59:00+00,2015-02-07 23:54:00+00
46188,46189,NaN,NaN,1,1987.0,15929,404,382,456,Subscriber,9 Ave & W 14 St,University Pl & E 14 St,-74.005509,40.740583,-73.992005,40.734927,2015-02-08 00:03:00+00,2015-02-07 23:55:00+00
46189,46190,NaN,NaN,1,1983.0,17541,466,254,327,Subscriber,W 25 St & 6 Ave,W 11 St & 6 Ave,-73.991449,40.743954,-73.998004,40.735324,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
46190,46191,NaN,NaN,2,1983.0,14736,494,116,306,Subscriber,W 26 St & 8 Ave,W 17 St & 8 Ave,-73.997236,40.747348,-74.001497,40.741776,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
46191,46192,NaN,NaN,1,1984.0,16300,432,495,1248,Subscriber,E 7 St & Avenue A,W 47 St & 10 Ave,-73.983799,40.726218,-73.993012,40.762699,2015-02-08 00:17:00+00,2015-02-07 23:56:00+00
46192,46193,NaN,NaN,1,1959.0,16978,325,152,1165,Subscriber,E 19 St & 3 Ave,Warren St & Church St,-73.984738,40.736245,-74.009106,40.714740,2015-02-08 00:15:00+00,2015-02-07 23:56:00+00
46193,46194,NaN,NaN,1,1974.0,16722,295,461,993,Subscriber,Pike St & E Broadway,E 20 St & 2 Ave,-73.992939,40.714067,-73.982050,40.735877,2015-02-08 00:13:00+00,2015-02-07 23:56:00+00
46194,46195,NaN,NaN,2,1960.0,20184,265,455,1422,Subscriber,Stanton St & Chrystie St,1 Ave & E 44 St,-73.991475,40.722293,-73.969053,40.750020,2015-02-08 00:20:00+00,2015-02-07 23:57:00+00
46195,46196,NaN,NaN,1,1953.0,15585,325,470,689,Subscriber,E 19 St & 3 Ave,W 20 St & 8 Ave,-73.984738,40.736245,-74.000040,40.743453,2015-02-08 00:08:00+00,2015-02-07 23:57:00+00
46196,46197,NaN,NaN,2,1986.0,16395,325,474,428,Subscriber,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:04:00+00,2015-02-07 23:57:00+00
46197,46198,NaN,NaN,1,1986.0,15545,325,474,392,Subscriber,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:03:00+00,2015-02-07 23:57:00+00
46198,46199,NaN,NaN,2,1983.0,19540,334,368,548,Subscriber,W 20 St & 7 Ave,Carmine St & 6 Ave,-73.997262,40.742388,-74.002150,40.730386,2015-02-08 00:08:00+00,2015-02-07 23:58:00+00
46199,46200,NaN,NaN,2,1965.0,20998,417,439,917,Subscriber,Barclay St & Church St,E 4 St & 2 Ave,-74.010202,40.712912,-73.989780,40.726281,2015-02-08 00:15:00+00,2015-02-07 23:59:00+00

## Task 1

### Sort data by start_station_id, tripduration. 
- Only checking trips with duration <= 3 hours

In [4]:
test = '''
SELECT * FROM citibike
WHERE tripduration <= 10800
ORDER BY start_station_id, tripduration
'''

In [5]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,8998,NaN,NaN,2,1980.0,19039,72,72,107,Subscriber,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-03 10:12:00+00,2015-02-03 10:10:00+00
1,40759,NaN,NaN,2,1959.0,18131,72,72,189,Subscriber,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:43:00+00,2015-02-07 10:40:00+00
2,40757,NaN,NaN,1,1995.0,19729,72,72,229,Subscriber,W 52 St & 11 Ave,W 52 St & 11 Ave,-73.993929,40.767272,-73.993929,40.767272,2015-02-07 10:44:00+00,2015-02-07 10:40:00+00
3,21948,NaN,NaN,1,1970.0,16879,478,72,248,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-05 06:24:00+00,2015-02-05 06:19:00+00
4,43099,NaN,NaN,1,1983.0,15277,515,72,252,Subscriber,W 43 St & 10 Ave,W 52 St & 11 Ave,-73.994618,40.760094,-73.993929,40.767272,2015-02-07 15:47:00+00,2015-02-07 15:43:00+00
5,32566,NaN,NaN,1,1971.0,18492,478,72,261,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-06 09:02:00+00,2015-02-06 08:58:00+00
6,15971,NaN,NaN,1,1961.0,19216,478,72,276,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-04 12:51:00+00,2015-02-04 12:46:00+00
7,41355,NaN,NaN,1,1974.0,21588,447,72,283,Subscriber,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-07 12:15:00+00,2015-02-07 12:10:00+00
8,42074,NaN,NaN,1,1978.0,19124,514,72,288,Subscriber,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-07 13:54:00+00,2015-02-07 13:50:00+00
9,2282,NaN,NaN,1,1974.0,18174,447,72,301,Subscriber,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-01 13:13:00+00,2015-02-01 13:08:00+00
10,44674,NaN,NaN,1,1983.0,18198,526,72,304,Subscriber,E 33 St & 5 Ave,W 52 St & 11 Ave,-73.984907,40.747659,-73.993929,40.767272,2015-02-07 18:36:00+00,2015-02-07 18:31:00+00
11,2142,NaN,NaN,1,1982.0,19672,478,72,339,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-01 13:00:00+00,2015-02-01 12:54:00+00
12,649,NaN,NaN,2,1986.0,14692,2021,72,344,Subscriber,W 45 St & 8 Ave,W 52 St & 11 Ave,-73.988597,40.759291,-73.993929,40.767272,2015-02-01 09:54:00+00,2015-02-01 09:49:00+00
13,44789,NaN,NaN,1,1983.0,17669,447,72,345,Subscriber,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-07 18:51:00+00,2015-02-07 18:46:00+00
14,9494,NaN,NaN,1,1961.0,16754,478,72,348,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-03 13:06:00+00,2015-02-03 13:01:00+00
15,42446,NaN,NaN,1,1983.0,21114,500,72,359,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-07 14:39:00+00,2015-02-07 14:33:00+00
16,41465,NaN,NaN,1,1970.0,19729,515,72,366,Subscriber,W 43 St & 10 Ave,W 52 St & 11 Ave,-73.994618,40.760094,-73.993929,40.767272,2015-02-07 12:36:00+00,2015-02-07 12:29:00+00
17,14395,NaN,NaN,1,1981.0,18620,500,72,367,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-04 09:05:00+00,2015-02-04 08:59:00+00
18,19984,NaN,NaN,1,1981.0,20119,450,72,373,Subscriber,W 49 St & 8 Ave,W 52 St & 11 Ave,-73.987882,40.762272,-73.993929,40.767272,2015-02-04 19:22:00+00,2015-02-04 19:16:00+00
19,8726,NaN,NaN,1,1981.0,20988,500,72,375,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-03 09:21:00+00,2015-02-03 09:15:00+00
20,25842,NaN,NaN,2,1972.0,16310,500,72,377,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 13:01:00+00,2015-02-05 12:55:00+00
21,26155,NaN,NaN,1,1978.0,18287,514,72,377,Subscriber,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-05 13:52:00+00,2015-02-05 13:46:00+00
22,25587,NaN,NaN,1,1973.0,18991,500,72,379,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 12:21:00+00,2015-02-05 12:15:00+00
23,24156,NaN,NaN,1,1981.0,20600,500,72,380,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-05 09:21:00+00,2015-02-05 09:14:00+00
24,27104,NaN,NaN,1,1973.0,15927,479,72,386,Subscriber,9 Ave & W 45 St,W 52 St & 11 Ave,-73.991255,40.760193,-73.993929,40.767272,2015-02-05 16:06:00+00,2015-02-05 16:00:00+00
25,3957,NaN,NaN,1,1991.0,15282,514,72,387,Subscriber,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-01 16:03:00+00,2015-02-01 15:57:00+00
26,9194,NaN,NaN,1,1980.0,17196,500,72,388,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-03 11:30:00+00,2015-02-03 11:23:00+00
27,31639,NaN,NaN,1,1978.0,16405,529,72,388,Subscriber,W 42 St & 8 Ave,W 52 St & 11 Ave,-73.990985,40.757570,-73.993929,40.767272,2015-02-06 08:00:00+00,2015-02-06 07:53:00+00
28,38564,NaN,NaN,1,1974.0,19771,500,72,396,Subscriber,Broadway & W 51 St,W 52 St & 11 Ave,-73.983362,40.762288,-73.993929,40.767272,2015-02-06 20:01:00+00,2015-02-06 19:55:00+00
29,33221,NaN,NaN,2,1986.0,17972,2021,72,396,Subscriber,W 45 St & 8 Ave,W 52 St & 11 Ave,-73.988597,40.759291,-73.993929,40.767272,2015-02-06 10:06:00+00,2015-02-06 09:59:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46121,31410,NaN,NaN,1,1958.0,17595,388,3002,1221,Subscriber,W 26 St & 10 Ave,South End Ave & Liberty St,-74.002950,40.749718,-74.015756,40.711512,2015-02-06 07:54:00+00,2015-02-06 07:33:00+00
46122,22533,NaN,NaN,1,1962.0,15178,434,3002,1240,Subscriber,9 Ave & W 18 St,South End Ave & Liberty St,-74.003664,40.743174,-74.015756,40.711512,2015-02-05 07:58:00+00,2015-02-05 07:37:00+00
46123,1333,NaN,NaN,0,NaN,18288,360,3002,1243,Customer,William St & Pine St,South End Ave & Liberty St,-74.008873,40.707179,-74.015756,40.711512,2015-02-01 11:48:00+00,2015-02-01 11:27:00+00
46124,23807,NaN,NaN,1,1974.0,16147,496,3002,1244,Subscriber,E 16 St & 5 Ave,South End Ave & Liberty St,-73.992390,40.737262,-74.015756,40.711512,2015-02-05 09:16:00+00,2015-02-05 08:55:00+00
46125,27637,NaN,NaN,1,1973.0,17061,521,3002,1285,Subscriber,8 Ave & W 31 St,South End Ave & Liberty St,-73.994811,40.750450,-74.015756,40.711512,2015-02-05 17:20:00+00,2015-02-05 16:59:00+00
46126,22399,NaN,NaN,1,1991.0,17198,459,3002,1312,Subscriber,W 20 St & 11 Ave,South End Ave & Liberty St,-74.007756,40.746745,-74.015756,40.711512,2015-02-05 07:48:00+00,2015-02-05 07:26:00+00
46127,24714,NaN,NaN,1,1958.0,20872,388,3002,1313,Subscriber,W 26 St & 10 Ave,South End Ave & Liberty St,-74.002950,40.749718,-74.015756,40.711512,2015-02-05 10:21:00+00,2015-02-05 10:00:00+00
46128,41541,NaN,NaN,1,1955.0,15495,168,3002,1332,Subscriber,W 18 St & 6 Ave,South End Ave & Liberty St,-73.994564,40.739713,-74.015756,40.711512,2015-02-07 13:02:00+00,2015-02-07 12:40:00+00
46129,43007,NaN,NaN,1,1966.0,20780,382,3002,1417,Subscriber,University Pl & E 14 St,South End Ave & Liberty St,-73.992005,40.734927,-74.015756,40.711512,2015-02-07 15:59:00+00,2015-02-07 15:35:00+00
46130,35349,NaN,NaN,1,1956.0,17077,334,3002,1445,Subscriber,W 20 St & 7 Ave,South End Ave & Liberty St,-73.997262,40.742388,-74.015756,40.711512,2015-02-06 16:02:00+00,2015-02-06 15:38:00+00
46131,20877,NaN,NaN,1,1986.0,20268,438,3002,1460,Subscriber,St Marks Pl & 1 Ave,South End Ave & Liberty St,-73.985649,40.727791,-74.015756,40.711512,2015-02-04 21:20:00+00,2015-02-04 20:56:00+00
46132,39913,NaN,NaN,1,1954.0,15586,514,3002,1485,Subscriber,12 Ave & W 40 St,South End Ave & Liberty St,-74.002777,40.760875,-74.015756,40.711512,2015-02-07 08:52:00+00,2015-02-07 08:27:00+00
46133,38954,NaN,NaN,1,1986.0,19331,438,3002,1521,Subscriber,St Marks Pl & 1 Ave,South End Ave & Liberty St,-73.985649,40.727791,-74.015756,40.711512,2015-02-06 21:36:00+00,2015-02-06 21:11:00+00
46134,30026,NaN,NaN,1,1949.0,15627,375,3002,1606,Subscriber,Mercer St & Bleecker St,South End Ave & Liberty St,-73.996951,40.726795,-74.015756,40.711512,2015-02-05 20:29:00+00,2015-02-05 20:02:00+00
46135,14538,NaN,NaN,1,1959.0,17488,494,3002,1626,Subscriber,W 26 St & 8 Ave,South End Ave & Liberty St,-73.997236,40.747348,-74.015756,40.711512,2015-02-04 09:39:00+00,2015-02-04 09:11:00+00
46136,2368,NaN,NaN,0,NaN,16918,478,3002,1666,Customer,11 Ave & W 41 St,South End Ave & Liberty St,-73.998842,40.760301,-74.015756,40.711512,2015-02-01 13:46:00+00,2015-02-01 13:18:00+00
46137,24145,NaN,NaN,1,1959.0,15102,494,3002,1716,Subscriber,W 26 St & 8 Ave,South End Ave & Liberty St,-73.997236,40.747348,-74.015756,40.711512,2015-02-05 09:43:00+00,2015-02-05 09:14:00+00
46138,32820,NaN,NaN,1,1959.0,15403,521,3002,1717,Subscriber,8 Ave & W 31 St,South End Ave & Liberty St,-73.994811,40.750450,-74.015756,40.711512,2015-02-06 09:48:00+00,2015-02-06 09:19:00+00
46139,35576,NaN,NaN,1,1969.0,21158,318,3002,1776,Subscriber,E 43 St & Vanderbilt Ave,South End Ave & Liberty St,-73.977987,40.753202,-74.015756,40.711512,2015-02-06 16:32:00+00,2015-02-06 16:02:00+00
46140,24214,NaN,NaN,1,1981.0,16496,449,3002,1823,Subscriber,W 52 St & 9 Ave,South End Ave & Liberty St,-73.987895,40.764618,-74.015756,40.711512,2015-02-05 09:50:00+00,2015-02-05 09:20:00+00
46141,17590,NaN,NaN,1,1969.0,20246,318,3002,1830,Subscriber,E 43 St & Vanderbilt Ave,South End Ave & Liberty St,-73.977987,40.753202,-74.015756,40.711512,2015-02-04 17:04:00+00,2015-02-04 16:33:00+00
46142,1228,NaN,NaN,0,NaN,17849,525,3002,1900,Customer,W 34 St & 11 Ave,South End Ave & Liberty St,-74.002116,40.755942,-74.015756,40.711512,2015-02-01 11:45:00+00,2015-02-01 11:14:00+00
46143,11587,NaN,NaN,1,1996.0,19133,279,3002,1908,Subscriber,Peck Slip & Front St,South End Ave & Liberty St,-74.001670,40.707873,-74.015756,40.711512,2015-02-03 19:26:00+00,2015-02-03 18:54:00+00
46144,44703,NaN,NaN,2,1964.0,15443,410,3002,1920,Subscriber,Suffolk St & Stanton St,South End Ave & Liberty St,-73.985180,40.720664,-74.015756,40.711512,2015-02-07 19:08:00+00,2015-02-07 18:36:00+00
46145,6781,NaN,NaN,1,1959.0,19665,494,3002,1976,Subscriber,W 26 St & 8 Ave,South End Ave & Liberty St,-73.997236,40.747348,-74.015756,40.711512,2015-02-02 09:53:00+00,2015-02-02 09:21:00+00
46146,27203,NaN,NaN,1,1969.0,20069,318,3002,1977,Subscriber,E 43 St & Vanderbilt Ave,South End Ave & Liberty St,-73.977987,40.753202,-74.015756,40.711512,2015-02-05 16:44:00+00,2015-02-05 16:11:00+00
46147,10173,NaN,NaN,1,1969.0,15309,318,3002,1977,Subscriber,E 43 St & Vanderbilt Ave,South End Ave & Liberty St,-73.977987,40.753202,-74.015756,40.711512,2015-02-03 16:37:00+00,2015-02-03 16:04:00+00
46148,23529,NaN,NaN,1,1985.0,21473,359,3002,2131,Subscriber,E 47 St & Park Ave,South End Ave & Liberty St,-73.974987,40.755103,-74.015756,40.711512,2015-02-05 09:17:00+00,2015-02-05 08:42:00+00
46149,8831,NaN,NaN,1,1958.0,15552,510,3002,2139,Subscriber,W 51 St & 6 Ave,South End Ave & Liberty St,-73.980420,40.760660,-74.015756,40.711512,2015-02-03 10:09:00+00,2015-02-03 09:33:00+00
46150,1506,NaN,NaN,0,NaN,21202,499,3002,7225,Customer,Broadway & W 60 St,South End Ave & Liberty St,-73.981918,40.769155,-74.015756,40.711512,2015-02-01 13:47:00+00,2015-02-01 11:46:00+00

### Only show the top/last 10 records (aka head and tail in SQL)

top 10

In [6]:
test = '''
SELECT * FROM citibike
WHERE tripduration <= 10800
ORDER BY start_station_id
LIMIT 10
'''

In [7]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,3302,NaN,NaN,1,1981.0,17429,499,72,569,Subscriber,Broadway & W 60 St,W 52 St & 11 Ave,-73.981918,40.769155,-73.993929,40.767272,2015-02-01 15:01:00+00,2015-02-01 14:52:00+00
1,1527,NaN,NaN,1,1977.0,16524,212,72,962,Subscriber,W 16 St & The High Line,W 52 St & 11 Ave,-74.006818,40.743349,-73.993929,40.767272,2015-02-01 12:03:00+00,2015-02-01 11:47:00+00
2,2142,NaN,NaN,1,1982.0,19672,478,72,339,Subscriber,11 Ave & W 41 St,W 52 St & 11 Ave,-73.998842,40.760301,-73.993929,40.767272,2015-02-01 13:00:00+00,2015-02-01 12:54:00+00
3,2282,NaN,NaN,1,1974.0,18174,447,72,301,Subscriber,8 Ave & W 52 St,W 52 St & 11 Ave,-73.985162,40.763707,-73.993929,40.767272,2015-02-01 13:13:00+00,2015-02-01 13:08:00+00
4,387,NaN,NaN,2,1972.0,20786,212,72,961,Subscriber,W 16 St & The High Line,W 52 St & 11 Ave,-74.006818,40.743349,-73.993929,40.767272,2015-02-01 08:54:00+00,2015-02-01 08:38:00+00
5,649,NaN,NaN,2,1986.0,14692,2021,72,344,Subscriber,W 45 St & 8 Ave,W 52 St & 11 Ave,-73.988597,40.759291,-73.993929,40.767272,2015-02-01 09:54:00+00,2015-02-01 09:49:00+00
6,1230,NaN,NaN,1,1969.0,17541,212,72,934,Subscriber,W 16 St & The High Line,W 52 St & 11 Ave,-74.006818,40.743349,-73.993929,40.767272,2015-02-01 11:30:00+00,2015-02-01 11:14:00+00
7,1983,NaN,NaN,0,NaN,17849,328,72,1944,Customer,Watts St & Greenwich St,W 52 St & 11 Ave,-74.009660,40.724055,-73.993929,40.767272,2015-02-01 13:12:00+00,2015-02-01 12:39:00+00
8,5136,NaN,NaN,1,1983.0,16427,529,72,455,Subscriber,W 42 St & 8 Ave,W 52 St & 11 Ave,-73.990985,40.757570,-73.993929,40.767272,2015-02-01 18:03:00+00,2015-02-01 17:55:00+00
9,3957,NaN,NaN,1,1991.0,15282,514,72,387,Subscriber,12 Ave & W 40 St,W 52 St & 11 Ave,-74.002777,40.760875,-73.993929,40.767272,2015-02-01 16:03:00+00,2015-02-01 15:57:00+00

last 10

In [8]:
test = '''
SELECT * FROM citibike
WHERE tripduration <= 10800
ORDER BY start_station_id DESC
LIMIT 10
'''

In [9]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,1228,NaN,NaN,0,NaN,17849,525,3002,1900,Customer,W 34 St & 11 Ave,South End Ave & Liberty St,-74.002116,40.755942,-74.015756,40.711512,2015-02-01 11:45:00+00,2015-02-01 11:14:00+00
1,1863,NaN,NaN,1,1996.0,19309,358,3002,689,Subscriber,Christopher St & Greenwich St,South End Ave & Liberty St,-74.007114,40.732916,-74.015756,40.711512,2015-02-01 12:36:00+00,2015-02-01 12:25:00+00
2,1472,NaN,NaN,2,1980.0,16987,308,3002,683,Subscriber,St James Pl & Oliver St,South End Ave & Liberty St,-73.998512,40.713079,-74.015756,40.711512,2015-02-01 11:55:00+00,2015-02-01 11:43:00+00
3,1506,NaN,NaN,0,NaN,21202,499,3002,7225,Customer,Broadway & W 60 St,South End Ave & Liberty St,-73.981918,40.769155,-74.015756,40.711512,2015-02-01 13:47:00+00,2015-02-01 11:46:00+00
4,1587,NaN,NaN,1,1959.0,15748,355,3002,858,Subscriber,Bayard St & Baxter St,South End Ave & Liberty St,-73.999744,40.716021,-74.015756,40.711512,2015-02-01 12:07:00+00,2015-02-01 11:53:00+00
5,1628,NaN,NaN,1,1980.0,20901,369,3002,745,Subscriber,Washington Pl & 6 Ave,South End Ave & Liberty St,-74.000264,40.732241,-74.015756,40.711512,2015-02-01 12:09:00+00,2015-02-01 11:57:00+00
6,293,NaN,NaN,2,1980.0,19484,417,3002,301,Subscriber,Barclay St & Church St,South End Ave & Liberty St,-74.010202,40.712912,-74.015756,40.711512,2015-02-01 07:54:00+00,2015-02-01 07:49:00+00
7,1333,NaN,NaN,0,NaN,18288,360,3002,1243,Customer,William St & Pine St,South End Ave & Liberty St,-74.008873,40.707179,-74.015756,40.711512,2015-02-01 11:48:00+00,2015-02-01 11:27:00+00
8,2205,NaN,NaN,1,1979.0,17004,368,3002,790,Subscriber,Carmine St & 6 Ave,South End Ave & Liberty St,-74.002150,40.730386,-74.015756,40.711512,2015-02-01 13:14:00+00,2015-02-01 13:01:00+00
9,2026,NaN,NaN,2,1984.0,18386,147,3002,307,Subscriber,Greenwich St & Warren St,South End Ave & Liberty St,-74.011220,40.715422,-74.015756,40.711512,2015-02-01 12:47:00+00,2015-02-01 12:42:00+00

### List all unique start_station_id values

In [10]:
test = '''
SELECT DISTINCT start_station_id FROM citibike
'''

In [11]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

     start_station_id  Unnamed: 1
0                 195         NaN
1                 251         NaN
2                 285         NaN
3                 120         NaN
4                 483         NaN
5                 264         NaN
6                 497         NaN
7                 305         NaN
8                 318         NaN
9                 312         NaN
10                496         NaN
11                455         NaN
12                470         NaN
13                276         NaN
14               2008         NaN
15                313         NaN
16                262         NaN
17                362         NaN
18                151         NaN
19                384         NaN
20                119         NaN
21                399         NaN
22                356         NaN
23                270         NaN
24                437         NaN
25                514         NaN
26                518         NaN
27                329         NaN
28                268         NaN
29                531         NaN
..                ...         ...
297               420         NaN
298               443         NaN
299               490         NaN
300               492         NaN
301               416         NaN
302               331         NaN
303               232         NaN
304               427         NaN
305               377         NaN
306               445         NaN
307               411         NaN
308               260         NaN
309               403         NaN
310               494         NaN
311               244         NaN
312               128         NaN
313               223         NaN
314               456         NaN
315               300         NaN
316               217         NaN
317               538         NaN
318               383         NaN
319               212         NaN
320               353         NaN
321               328         NaN
322               216         NaN
323               263         NaN
324               266         NaN
325               144         NaN
326               453         NaN

[327 rows x 2 columns]

### Aggregation functions:
- Count the number of trips (aka wc -l in SQL)

In [12]:
test = '''
SELECT COUNT(tripduration) AS nums FROM citibike
'''

In [13]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

    nums  Unnamed: 1
0  46200         NaN

- Find the average/min/max trip duration

In [14]:
test = '''
SELECT AVG(tripduration) AS tripaverage, 
       MIN(tripduration) AS tripmin, 
       MAX(tripduration) AS tripmax 
       FROM citibike
'''

In [15]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   tripaverage  tripmin  tripmax
0   675.865823       60    43016

## Task 2

### Selecting trips started on Feb-02-2015 only

In [16]:
test = '''
SELECT * FROM citibike 
WHERE starttime >= '2015-02-02 00:00:00'
AND starttime < '2015-02-03 00:00:00'
'''

In [17]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,6442,NaN,NaN,1,1992.0,20684,489,442,199,Subscriber,10 Ave & W 28 St,W 27 St & 7 Ave,-74.001768,40.750664,-73.993915,40.746647,2015-02-02 00:05:00+00,2015-02-02 00:02:00+00
1,6443,NaN,NaN,2,1964.0,16094,349,326,418,Subscriber,Rivington St & Ridge St,E 11 St & 1 Ave,-73.983299,40.718502,-73.984267,40.729538,2015-02-02 00:10:00+00,2015-02-02 00:03:00+00
2,6444,NaN,NaN,1,1974.0,17362,415,279,276,Subscriber,Pearl St & Hanover Square,Peck Slip & Front St,-74.009260,40.704718,-74.001670,40.707873,2015-02-02 00:09:00+00,2015-02-02 00:04:00+00
3,6445,NaN,NaN,2,1992.0,15475,237,496,420,Subscriber,E 11 St & 2 Ave,E 16 St & 5 Ave,-73.986724,40.730473,-73.992390,40.737262,2015-02-02 00:13:00+00,2015-02-02 00:06:00+00
4,6446,NaN,NaN,1,1968.0,16272,450,477,304,Subscriber,W 49 St & 8 Ave,W 41 St & 8 Ave,-73.987882,40.762272,-73.990026,40.756405,2015-02-02 00:12:00+00,2015-02-02 00:07:00+00
5,6447,NaN,NaN,1,1979.0,16370,391,467,622,Subscriber,Clark St & Henry St,Dean St & 4 Ave,-73.993446,40.697601,-73.978951,40.683125,2015-02-02 00:18:00+00,2015-02-02 00:08:00+00
6,6448,NaN,NaN,1,1963.0,19437,482,434,371,Subscriber,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 00:15:00+00,2015-02-02 00:09:00+00
7,6449,NaN,NaN,1,1982.0,21211,2008,330,477,Subscriber,Little West St & 1 Pl,Reade St & Broadway,-74.016777,40.705693,-74.005628,40.714505,2015-02-02 00:19:00+00,2015-02-02 00:11:00+00
8,6450,NaN,NaN,2,1978.0,21417,423,521,743,Subscriber,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-02 00:25:00+00,2015-02-02 00:12:00+00
9,6451,NaN,NaN,1,1956.0,15722,453,504,599,Subscriber,W 22 St & 8 Ave,1 Ave & E 15 St,-73.999154,40.744751,-73.981656,40.732219,2015-02-02 00:22:00+00,2015-02-02 00:12:00+00
10,6452,NaN,NaN,1,1962.0,18972,236,285,345,Subscriber,St Marks Pl & 2 Ave,Broadway & E 14 St,-73.987140,40.728419,-73.990741,40.734546,2015-02-02 00:18:00+00,2015-02-02 00:12:00+00
11,6453,NaN,NaN,1,1980.0,19628,476,301,721,Subscriber,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-02 00:25:00+00,2015-02-02 00:13:00+00
12,6454,NaN,NaN,1,1978.0,15169,376,279,182,Subscriber,John St & William St,Peck Slip & Front St,-74.007222,40.708621,-74.001670,40.707873,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
13,6455,NaN,NaN,1,1997.0,17533,411,342,154,Subscriber,E 6 St & Avenue D,Columbia St & Rivington St,-73.976687,40.722281,-73.980166,40.717400,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
14,6456,NaN,NaN,1,1983.0,19761,491,470,435,Subscriber,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-02 00:21:00+00,2015-02-02 00:14:00+00
15,6457,NaN,NaN,1,1993.0,17267,393,236,310,Subscriber,E 5 St & Avenue C,St Marks Pl & 2 Ave,-73.979955,40.722992,-73.987140,40.728419,2015-02-02 00:20:00+00,2015-02-02 00:15:00+00
16,6458,NaN,NaN,1,1964.0,18691,470,470,1274,Subscriber,W 20 St & 8 Ave,W 20 St & 8 Ave,-74.000040,40.743453,-74.000040,40.743453,2015-02-02 00:37:00+00,2015-02-02 00:16:00+00
17,6459,NaN,NaN,1,1977.0,17106,174,485,642,Subscriber,E 25 St & 1 Ave,W 37 St & 5 Ave,-73.977387,40.738177,-73.983390,40.750380,2015-02-02 00:29:00+00,2015-02-02 00:18:00+00
18,6460,NaN,NaN,1,1973.0,20009,483,345,256,Subscriber,E 12 St & 3 Ave,W 13 St & 6 Ave,-73.988900,40.732233,-73.997044,40.736494,2015-02-02 00:22:00+00,2015-02-02 00:18:00+00
19,6461,NaN,NaN,1,1979.0,18777,442,489,334,Subscriber,W 27 St & 7 Ave,10 Ave & W 28 St,-73.993915,40.746647,-74.001768,40.750664,2015-02-02 00:25:00+00,2015-02-02 00:19:00+00
20,6462,NaN,NaN,1,1989.0,15357,174,507,90,Subscriber,E 25 St & 1 Ave,E 25 St & 2 Ave,-73.977387,40.738177,-73.979738,40.739126,2015-02-02 00:20:00+00,2015-02-02 00:19:00+00
21,6463,NaN,NaN,1,1983.0,18487,405,380,203,Subscriber,Washington St & Gansevoort St,W 4 St & 7 Ave S,-74.008119,40.739323,-74.002939,40.734011,2015-02-02 00:23:00+00,2015-02-02 00:20:00+00
22,6464,NaN,NaN,1,1981.0,20863,439,334,649,Subscriber,E 4 St & 2 Ave,W 20 St & 7 Ave,-73.989780,40.726281,-73.997262,40.742388,2015-02-02 00:32:00+00,2015-02-02 00:22:00+00
23,6465,NaN,NaN,1,1970.0,16539,448,508,319,Subscriber,W 37 St & 10 Ave,W 46 St & 11 Ave,-73.997901,40.756604,-73.996674,40.763414,2015-02-02 00:29:00+00,2015-02-02 00:23:00+00
24,6466,NaN,NaN,1,1961.0,18737,301,428,154,Subscriber,E 2 St & Avenue B,E 3 St & 1 Ave,-73.983688,40.722174,-73.987834,40.724677,2015-02-02 00:30:00+00,2015-02-02 00:27:00+00
25,6467,NaN,NaN,2,1980.0,17797,195,331,550,Subscriber,Liberty St & Broadway,Pike St & Monroe St,-74.010434,40.709056,-73.991930,40.711731,2015-02-02 00:37:00+00,2015-02-02 00:28:00+00
26,6468,NaN,NaN,1,1990.0,20638,478,529,268,Subscriber,11 Ave & W 41 St,W 42 St & 8 Ave,-73.998842,40.760301,-73.990985,40.757570,2015-02-02 00:34:00+00,2015-02-02 00:29:00+00
27,6469,NaN,NaN,1,1989.0,17636,366,421,153,Subscriber,Clinton Ave & Myrtle Ave,Clermont Ave & Park Ave,-73.968896,40.693261,-73.971297,40.695734,2015-02-02 00:31:00+00,2015-02-02 00:29:00+00
28,6470,NaN,NaN,1,1982.0,18472,494,284,309,Subscriber,W 26 St & 8 Ave,Greenwich Ave & 8 Ave,-73.997236,40.747348,-74.002638,40.739017,2015-02-02 00:36:00+00,2015-02-02 00:31:00+00
29,6471,NaN,NaN,1,1968.0,17456,252,383,138,Subscriber,MacDougal St & Washington Sq,Greenwich Ave & Charles St,-73.998522,40.732264,-74.000271,40.735238,2015-02-02 00:35:00+00,2015-02-02 00:33:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,7871,NaN,NaN,1,1985.0,20572,380,312,722,Subscriber,W 4 St & 7 Ave S,Allen St & E Houston St,-74.002939,40.734011,-73.989111,40.722055,2015-02-02 23:20:00+00,2015-02-02 23:08:00+00
1430,7872,NaN,NaN,1,1981.0,20338,491,486,274,Subscriber,E 24 St & Park Ave S,Broadway & W 29 St,-73.986022,40.740964,-73.988557,40.746201,2015-02-02 23:12:00+00,2015-02-02 23:08:00+00
1431,7873,NaN,NaN,1,1978.0,15826,515,352,951,Subscriber,W 43 St & 10 Ave,W 56 St & 6 Ave,-73.994618,40.760094,-73.977225,40.763406,2015-02-02 23:27:00+00,2015-02-02 23:11:00+00
1432,7874,NaN,NaN,1,1990.0,18325,521,489,276,Subscriber,8 Ave & W 31 St,10 Ave & W 28 St,-73.994811,40.750450,-74.001768,40.750664,2015-02-02 23:20:00+00,2015-02-02 23:16:00+00
1433,7875,NaN,NaN,1,1977.0,16654,434,494,426,Subscriber,9 Ave & W 18 St,W 26 St & 8 Ave,-74.003664,40.743174,-73.997236,40.747348,2015-02-02 23:24:00+00,2015-02-02 23:17:00+00
1434,7876,NaN,NaN,1,1966.0,20902,229,402,578,Subscriber,Great Jones St,Broadway & E 22 St,-73.993790,40.727434,-73.989551,40.740343,2015-02-02 23:28:00+00,2015-02-02 23:19:00+00
1435,7877,NaN,NaN,1,1954.0,20796,2017,164,2621,Subscriber,E 43 St & 2 Ave,E 47 St & 2 Ave,-73.971214,40.750224,-73.970325,40.753231,2015-02-03 00:06:00+00,2015-02-02 23:22:00+00
1436,7878,NaN,NaN,1,1989.0,20160,449,498,621,Subscriber,W 52 St & 9 Ave,Broadway & W 32 St,-73.987895,40.764618,-73.988084,40.748549,2015-02-02 23:32:00+00,2015-02-02 23:22:00+00
1437,7879,NaN,NaN,1,1974.0,17392,477,521,323,Subscriber,W 41 St & 8 Ave,8 Ave & W 31 St,-73.990026,40.756405,-73.994811,40.750450,2015-02-02 23:29:00+00,2015-02-02 23:23:00+00
1438,7880,NaN,NaN,1,1963.0,17263,482,434,393,Subscriber,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 23:31:00+00,2015-02-02 23:24:00+00
1439,7881,NaN,NaN,1,1955.0,19858,497,161,597,Subscriber,E 17 St & Broadway,LaGuardia Pl & W 3 St,-73.990093,40.737050,-73.998102,40.729170,2015-02-02 23:35:00+00,2015-02-02 23:25:00+00
1440,7882,NaN,NaN,1,1979.0,20319,462,494,244,Subscriber,W 22 St & 10 Ave,W 26 St & 8 Ave,-74.004519,40.746920,-73.997236,40.747348,2015-02-02 23:30:00+00,2015-02-02 23:25:00+00
1441,7883,NaN,NaN,1,1977.0,21600,127,306,1023,Subscriber,Barrow St & Hudson St,Cliff St & Fulton St,-74.006744,40.731724,-74.005301,40.708235,2015-02-02 23:43:00+00,2015-02-02 23:26:00+00
1442,7884,NaN,NaN,1,1986.0,18791,473,349,419,Subscriber,Rivington St & Chrystie St,Rivington St & Ridge St,-73.991925,40.721101,-73.983299,40.718502,2015-02-02 23:38:00+00,2015-02-02 23:31:00+00
1443,7885,NaN,NaN,1,1966.0,17730,358,450,1429,Subscriber,Christopher St & Greenwich St,W 49 St & 8 Ave,-74.007114,40.732916,-73.987882,40.762272,2015-02-02 23:55:00+00,2015-02-02 23:32:00+00
1444,7886,NaN,NaN,1,1980.0,18147,477,519,676,Subscriber,W 41 St & 8 Ave,Pershing Square North,-73.990026,40.756405,-73.977706,40.751873,2015-02-02 23:44:00+00,2015-02-02 23:32:00+00
1445,7887,NaN,NaN,1,1959.0,20249,489,546,879,Subscriber,10 Ave & W 28 St,E 30 St & Park Ave S,-74.001768,40.750664,-73.983035,40.744449,2015-02-02 23:48:00+00,2015-02-02 23:33:00+00
1446,7888,NaN,NaN,1,1988.0,18078,432,336,593,Subscriber,E 7 St & Avenue A,Sullivan St & Washington Sq,-73.983799,40.726218,-73.999061,40.730477,2015-02-02 23:45:00+00,2015-02-02 23:35:00+00
1447,7889,NaN,NaN,1,1983.0,16808,164,529,839,Subscriber,E 47 St & 2 Ave,W 42 St & 8 Ave,-73.970325,40.753231,-73.990985,40.757570,2015-02-02 23:50:00+00,2015-02-02 23:36:00+00
1448,7890,NaN,NaN,1,1986.0,21355,368,402,560,Subscriber,Carmine St & 6 Ave,Broadway & E 22 St,-74.002150,40.730386,-73.989551,40.740343,2015-02-02 23:46:00+00,2015-02-02 23:37:00+00
1449,7891,NaN,NaN,1,1994.0,15359,511,504,165,Subscriber,E 14 St & Avenue B,1 Ave & E 15 St,-73.977724,40.729387,-73.981656,40.732219,2015-02-02 23:40:00+00,2015-02-02 23:37:00+00
1450,7892,NaN,NaN,2,1982.0,18250,489,505,813,Subscriber,10 Ave & W 28 St,6 Ave & W 33 St,-74.001768,40.750664,-73.988484,40.749013,2015-02-02 23:56:00+00,2015-02-02 23:42:00+00
1451,7893,NaN,NaN,1,1987.0,16969,507,509,764,Subscriber,E 25 St & 2 Ave,9 Ave & W 22 St,-73.979738,40.739126,-74.001971,40.745497,2015-02-02 23:55:00+00,2015-02-02 23:42:00+00
1452,7894,NaN,NaN,1,1979.0,18825,397,496,2111,Subscriber,Fulton St & Clermont Ave,E 16 St & 5 Ave,-73.969223,40.684157,-73.992390,40.737262,2015-02-03 00:18:00+00,2015-02-02 23:43:00+00
1453,7895,NaN,NaN,1,1983.0,19000,439,280,518,Subscriber,E 4 St & 2 Ave,E 10 St & 5 Ave,-73.989780,40.726281,-73.995101,40.733320,2015-02-02 23:52:00+00,2015-02-02 23:43:00+00
1454,7896,NaN,NaN,1,1977.0,20723,440,484,371,Subscriber,E 45 St & 3 Ave,W 44 St & 5 Ave,-73.972826,40.752554,-73.980144,40.755003,2015-02-02 23:52:00+00,2015-02-02 23:45:00+00
1455,7897,NaN,NaN,1,1988.0,16528,417,224,188,Subscriber,Barclay St & Church St,Spruce St & Nassau St,-74.010202,40.712912,-74.005524,40.711464,2015-02-02 23:50:00+00,2015-02-02 23:47:00+00
1456,7898,NaN,NaN,1,1988.0,16541,394,345,689,Subscriber,E 9 St & Avenue C,W 13 St & 6 Ave,-73.977688,40.725213,-73.997044,40.736494,2015-02-03 00:02:00+00,2015-02-02 23:50:00+00
1457,7899,NaN,NaN,1,1961.0,14878,537,453,634,Subscriber,Lexington Ave & E 24 St,W 22 St & 8 Ave,-73.984092,40.740259,-73.999154,40.744751,2015-02-03 00:05:00+00,2015-02-02 23:55:00+00
1458,7900,NaN,NaN,2,1976.0,16326,302,285,733,Subscriber,Avenue D & E 3 St,Broadway & E 14 St,-73.977932,40.720828,-73.990741,40.734546,2015-02-03 00:10:00+00,2015-02-02 23:58:00+00

### Selecting trips started on the weekends

In [18]:
test = '''
SELECT * FROM citibike 
WHERE extract(ISODOW FROM starttime) in (6,7)
'''

In [19]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,5960,NaN,NaN,1,1965.0,19217,462,435,351,Subscriber,W 22 St & 10 Ave,W 21 St & 6 Ave,-74.004519,40.746920,-73.994156,40.741740,2015-02-01 20:42:00+00,2015-02-01 20:36:00+00
1,1,NaN,NaN,2,1978.0,17131,423,521,801,Subscriber,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-01 00:14:00+00,2015-02-01 00:00:00+00
2,2,NaN,NaN,1,1993.0,21289,504,497,379,Subscriber,1 Ave & E 15 St,E 17 St & Broadway,-73.981656,40.732219,-73.990093,40.737050,2015-02-01 00:07:00+00,2015-02-01 00:00:00+00
3,3,NaN,NaN,2,1969.0,18903,127,281,2474,Subscriber,Barrow St & Hudson St,Grand Army Plaza & Central Park S,-74.006744,40.731724,-73.973715,40.764397,2015-02-01 00:42:00+00,2015-02-01 00:01:00+00
4,4,NaN,NaN,2,1985.0,21044,505,2004,818,Subscriber,6 Ave & W 33 St,6 Ave & Broome St,-73.988484,40.749013,-74.004704,40.724399,2015-02-01 00:15:00+00,2015-02-01 00:01:00+00
5,5,NaN,NaN,1,1957.0,19868,83,323,544,Subscriber,Atlantic Ave & Fort Greene Pl,Lawrence St & Willoughby St,-73.976323,40.683826,-73.986317,40.692362,2015-02-01 00:10:00+00,2015-02-01 00:01:00+00
6,6,NaN,NaN,1,1979.0,15854,2002,373,717,Subscriber,Wythe Ave & Metropolitan Ave,Willoughby Ave & Walworth St,-73.963198,40.716887,-73.953820,40.693317,2015-02-01 00:14:00+00,2015-02-01 00:02:00+00
7,7,NaN,NaN,1,1983.0,15173,504,352,1306,Subscriber,1 Ave & E 15 St,W 56 St & 6 Ave,-73.981656,40.732219,-73.977225,40.763406,2015-02-01 00:26:00+00,2015-02-01 00:04:00+00
8,8,NaN,NaN,1,1955.0,17862,116,439,913,Subscriber,W 17 St & 8 Ave,E 4 St & 2 Ave,-74.001497,40.741776,-73.989780,40.726281,2015-02-01 00:19:00+00,2015-02-01 00:04:00+00
9,9,NaN,NaN,2,1985.0,21183,2012,335,759,Subscriber,E 27 St & 1 Ave,Washington Pl & Broadway,-73.976806,40.739445,-73.994046,40.729039,2015-02-01 00:17:00+00,2015-02-01 00:04:00+00
10,10,NaN,NaN,1,1982.0,14843,444,284,585,Subscriber,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
11,11,NaN,NaN,2,1988.0,16936,444,284,581,Subscriber,Broadway & W 24 St,Greenwich Ave & 8 Ave,-73.989151,40.742354,-74.002638,40.739017,2015-02-01 00:15:00+00,2015-02-01 00:05:00+00
12,12,NaN,NaN,2,1991.0,21507,472,498,204,Subscriber,E 32 St & Park Ave,Broadway & W 32 St,-73.981948,40.745712,-73.988084,40.748549,2015-02-01 00:08:00+00,2015-02-01 00:05:00+00
13,13,NaN,NaN,2,1982.0,17456,307,368,1169,Subscriber,Canal St & Rutgers St,Carmine St & 6 Ave,-73.989900,40.714275,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:07:00+00
14,14,NaN,NaN,2,1990.0,14679,2012,326,419,Subscriber,E 27 St & 1 Ave,E 11 St & 1 Ave,-73.976806,40.739445,-73.984267,40.729538,2015-02-01 00:14:00+00,2015-02-01 00:07:00+00
15,15,NaN,NaN,1,1977.0,18978,212,285,527,Subscriber,W 16 St & The High Line,Broadway & E 14 St,-74.006818,40.743349,-73.990741,40.734546,2015-02-01 00:17:00+00,2015-02-01 00:09:00+00
16,16,NaN,NaN,1,1968.0,16496,488,368,1013,Subscriber,W 39 St & 9 Ave,Carmine St & 6 Ave,-73.993722,40.756458,-74.002150,40.730386,2015-02-01 00:27:00+00,2015-02-01 00:10:00+00
17,17,NaN,NaN,1,1990.0,17107,331,394,587,Subscriber,Pike St & Monroe St,E 9 St & Avenue C,-73.991930,40.711731,-73.977688,40.725213,2015-02-01 00:23:00+00,2015-02-01 00:13:00+00
18,18,NaN,NaN,1,1987.0,16984,507,326,525,Subscriber,E 25 St & 2 Ave,E 11 St & 1 Ave,-73.979738,40.739126,-73.984267,40.729538,2015-02-01 00:22:00+00,2015-02-01 00:13:00+00
19,19,NaN,NaN,1,1980.0,15997,305,493,670,Subscriber,E 58 St & 3 Ave,W 45 St & 6 Ave,-73.967245,40.760958,-73.982912,40.756800,2015-02-01 00:26:00+00,2015-02-01 00:14:00+00
20,20,NaN,NaN,1,1960.0,21516,223,445,711,Subscriber,W 13 St & 7 Ave,E 10 St & Avenue A,-73.999947,40.737815,-73.981420,40.727408,2015-02-01 00:27:00+00,2015-02-01 00:15:00+00
21,21,NaN,NaN,1,1986.0,15815,457,428,1559,Subscriber,Broadway & W 58 St,E 3 St & 1 Ave,-73.981693,40.766953,-73.987834,40.724677,2015-02-01 00:42:00+00,2015-02-01 00:16:00+00
22,22,NaN,NaN,1,1987.0,18727,477,228,683,Subscriber,W 41 St & 8 Ave,E 48 St & 3 Ave,-73.990026,40.756405,-73.971879,40.754601,2015-02-01 00:27:00+00,2015-02-01 00:16:00+00
23,23,NaN,NaN,1,1969.0,14982,488,513,522,Subscriber,W 39 St & 9 Ave,W 56 St & 10 Ave,-73.993722,40.756458,-73.988639,40.768254,2015-02-01 00:24:00+00,2015-02-01 00:16:00+00
24,24,NaN,NaN,1,1957.0,16391,518,507,389,Subscriber,E 39 St & 2 Ave,E 25 St & 2 Ave,-73.973442,40.747804,-73.979738,40.739126,2015-02-01 00:23:00+00,2015-02-01 00:16:00+00
25,25,NaN,NaN,1,1981.0,15947,473,439,276,Subscriber,Rivington St & Chrystie St,E 4 St & 2 Ave,-73.991925,40.721101,-73.989780,40.726281,2015-02-01 00:21:00+00,2015-02-01 00:16:00+00
26,26,NaN,NaN,1,1993.0,16917,531,128,907,Subscriber,Forsyth St & Broome St,MacDougal St & Prince St,-73.992663,40.718939,-74.002971,40.727103,2015-02-01 00:32:00+00,2015-02-01 00:17:00+00
27,27,NaN,NaN,1,1975.0,15924,528,490,946,Subscriber,2 Ave & E 31 St,8 Ave & W 33 St,-73.977061,40.742909,-73.993934,40.751551,2015-02-01 00:33:00+00,2015-02-01 00:18:00+00
28,28,NaN,NaN,1,1973.0,21321,502,350,144,Subscriber,Henry St & Grand St,Clinton St & Grand St,-73.981346,40.714215,-73.987030,40.715595,2015-02-01 00:21:00+00,2015-02-01 00:18:00+00
29,29,NaN,NaN,2,1973.0,16861,401,250,257,Subscriber,Allen St & Rivington St,Lafayette St & Jersey St,-73.989978,40.720196,-73.995653,40.724561,2015-02-01 00:23:00+00,2015-02-01 00:19:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13201,46171,NaN,NaN,1,1988.0,15733,435,335,812,Subscriber,W 21 St & 6 Ave,Washington Pl & Broadway,-73.994156,40.741740,-73.994046,40.729039,2015-02-08 00:05:00+00,2015-02-07 23:51:00+00
13202,46172,NaN,NaN,1,1995.0,16931,504,361,647,Subscriber,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:51:00+00
13203,46173,NaN,NaN,1,1987.0,17202,401,152,563,Subscriber,Allen St & Rivington St,Warren St & Church St,-73.989978,40.720196,-74.009106,40.714740,2015-02-08 00:00:00+00,2015-02-07 23:51:00+00
13204,46174,NaN,NaN,2,1989.0,20314,439,483,470,Subscriber,E 4 St & 2 Ave,E 12 St & 3 Ave,-73.989780,40.726281,-73.988900,40.732233,2015-02-07 23:59:00+00,2015-02-07 23:51:00+00
13205,46175,NaN,NaN,1,1989.0,21531,395,467,299,Subscriber,Bond St & Schermerhorn St,Dean St & 4 Ave,-73.984106,40.688070,-73.978951,40.683125,2015-02-07 23:56:00+00,2015-02-07 23:51:00+00
13206,46176,NaN,NaN,1,1968.0,21491,504,361,629,Subscriber,1 Ave & E 15 St,Allen St & Hester St,-73.981656,40.732219,-73.991908,40.716059,2015-02-08 00:02:00+00,2015-02-07 23:52:00+00
13207,46177,NaN,NaN,1,1990.0,15367,380,402,499,Subscriber,W 4 St & 7 Ave S,Broadway & E 22 St,-74.002939,40.734011,-73.989551,40.740343,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
13208,46178,NaN,NaN,2,1973.0,18978,368,369,474,Subscriber,Carmine St & 6 Ave,Washington Pl & 6 Ave,-74.002150,40.730386,-74.000264,40.732241,2015-02-08 00:00:00+00,2015-02-07 23:52:00+00
13209,46179,NaN,NaN,1,1980.0,19507,504,476,345,Subscriber,1 Ave & E 15 St,E 31 St & 3 Ave,-73.981656,40.732219,-73.979661,40.743943,2015-02-07 23:58:00+00,2015-02-07 23:52:00+00
13210,46180,NaN,NaN,1,1980.0,16936,160,499,829,Subscriber,E 37 St & Lexington Ave,Broadway & W 60 St,-73.978311,40.748238,-73.981918,40.769155,2015-02-08 00:07:00+00,2015-02-07 23:53:00+00
13211,46181,NaN,NaN,1,1982.0,18689,531,368,776,Subscriber,Forsyth St & Broome St,Carmine St & 6 Ave,-73.992663,40.718939,-74.002150,40.730386,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
13212,46182,NaN,NaN,1,1972.0,15781,478,520,697,Subscriber,11 Ave & W 41 St,W 52 St & 5 Ave,-73.998842,40.760301,-73.976485,40.759923,2015-02-08 00:05:00+00,2015-02-07 23:53:00+00
13213,46183,NaN,NaN,1,1988.0,15081,471,467,1703,Subscriber,Grand St & Havemeyer St,Dean St & 4 Ave,-73.956981,40.712868,-73.978951,40.683125,2015-02-08 00:23:00+00,2015-02-07 23:54:00+00
13214,46184,NaN,NaN,1,1983.0,21672,247,479,922,Subscriber,Perry St & Bleecker St,9 Ave & W 45 St,-74.004831,40.735354,-73.991255,40.760193,2015-02-08 00:10:00+00,2015-02-07 23:54:00+00
13215,46185,NaN,NaN,1,1970.0,16336,488,457,849,Subscriber,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
13216,46186,NaN,NaN,1,1973.0,21609,488,457,826,Subscriber,W 39 St & 9 Ave,Broadway & W 58 St,-73.993722,40.756458,-73.981693,40.766953,2015-02-08 00:08:00+00,2015-02-07 23:54:00+00
13217,46187,NaN,NaN,1,1964.0,19470,3002,328,473,Subscriber,South End Ave & Liberty St,Watts St & Greenwich St,-74.015756,40.711512,-74.009660,40.724055,2015-02-08 00:02:00+00,2015-02-07 23:54:00+00
13218,46188,NaN,NaN,1,1960.0,18167,450,510,332,Subscriber,W 49 St & 8 Ave,W 51 St & 6 Ave,-73.987882,40.762272,-73.980420,40.760660,2015-02-07 23:59:00+00,2015-02-07 23:54:00+00
13219,46189,NaN,NaN,1,1987.0,15929,404,382,456,Subscriber,9 Ave & W 14 St,University Pl & E 14 St,-74.005509,40.740583,-73.992005,40.734927,2015-02-08 00:03:00+00,2015-02-07 23:55:00+00
13220,46190,NaN,NaN,1,1983.0,17541,466,254,327,Subscriber,W 25 St & 6 Ave,W 11 St & 6 Ave,-73.991449,40.743954,-73.998004,40.735324,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
13221,46191,NaN,NaN,2,1983.0,14736,494,116,306,Subscriber,W 26 St & 8 Ave,W 17 St & 8 Ave,-73.997236,40.747348,-74.001497,40.741776,2015-02-08 00:01:00+00,2015-02-07 23:55:00+00
13222,46192,NaN,NaN,1,1984.0,16300,432,495,1248,Subscriber,E 7 St & Avenue A,W 47 St & 10 Ave,-73.983799,40.726218,-73.993012,40.762699,2015-02-08 00:17:00+00,2015-02-07 23:56:00+00
13223,46193,NaN,NaN,1,1959.0,16978,325,152,1165,Subscriber,E 19 St & 3 Ave,Warren St & Church St,-73.984738,40.736245,-74.009106,40.714740,2015-02-08 00:15:00+00,2015-02-07 23:56:00+00
13224,46194,NaN,NaN,1,1974.0,16722,295,461,993,Subscriber,Pike St & E Broadway,E 20 St & 2 Ave,-73.992939,40.714067,-73.982050,40.735877,2015-02-08 00:13:00+00,2015-02-07 23:56:00+00
13225,46195,NaN,NaN,2,1960.0,20184,265,455,1422,Subscriber,Stanton St & Chrystie St,1 Ave & E 44 St,-73.991475,40.722293,-73.969053,40.750020,2015-02-08 00:20:00+00,2015-02-07 23:57:00+00
13226,46196,NaN,NaN,1,1953.0,15585,325,470,689,Subscriber,E 19 St & 3 Ave,W 20 St & 8 Ave,-73.984738,40.736245,-74.000040,40.743453,2015-02-08 00:08:00+00,2015-02-07 23:57:00+00
13227,46197,NaN,NaN,2,1986.0,16395,325,474,428,Subscriber,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:04:00+00,2015-02-07 23:57:00+00
13228,46198,NaN,NaN,1,1986.0,15545,325,474,392,Subscriber,E 19 St & 3 Ave,5 Ave & E 29 St,-73.984738,40.736245,-73.986831,40.745168,2015-02-08 00:03:00+00,2015-02-07 23:57:00+00
13229,46199,NaN,NaN,2,1983.0,19540,334,368,548,Subscriber,W 20 St & 7 Ave,Carmine St & 6 Ave,-73.997262,40.742388,-74.002150,40.730386,2015-02-08 00:08:00+00,2015-02-07 23:58:00+00
13230,46200,NaN,NaN,2,1965.0,20998,417,439,917,Subscriber,Barclay St & Church St,E 4 St & 2 Ave,-74.010202,40.712912,-73.989780,40.726281,2015-02-08 00:15:00+00,2015-02-07 23:59:00+00

- What are average trip duration during weekends?

In [20]:
test = '''
SELECT AVG(tripduration) AS tripaverage FROM citibike
WHERE extract(ISODOW FROM starttime) in (6,7)
'''

In [21]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   tripaverage  Unnamed: 1
0   662.942181         NaN

### Can we do the same for weekday?

In [22]:
test = '''
SELECT * FROM citibike
WHERE extract(ISODOW FROM starttime) not in (6,7)
'''

In [23]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,cartodb_id,the_geom,the_geom_webmercator,gender,birth_year,bikeid,end_station_id,start_station_id,tripduration,usertype,end_station_name,start_station_name,end_station_longitude,end_station_latitude,start_station_longitude,start_station_latitude,stoptime,starttime
0,9806,NaN,NaN,1,1971.0,17575,488,167,643,Subscriber,W 39 St & 9 Ave,E 39 St & 3 Ave,-73.993722,40.756458,-73.976049,40.748901,2015-02-03 14:50:00+00,2015-02-03 14:39:00+00
1,13113,NaN,NaN,1,1973.0,20313,440,332,1379,Subscriber,E 45 St & 3 Ave,Cherry St,-73.972826,40.752554,-73.979481,40.712199,2015-02-04 07:30:00+00,2015-02-04 07:07:00+00
2,6442,NaN,NaN,1,1992.0,20684,489,442,199,Subscriber,10 Ave & W 28 St,W 27 St & 7 Ave,-74.001768,40.750664,-73.993915,40.746647,2015-02-02 00:05:00+00,2015-02-02 00:02:00+00
3,6443,NaN,NaN,2,1964.0,16094,349,326,418,Subscriber,Rivington St & Ridge St,E 11 St & 1 Ave,-73.983299,40.718502,-73.984267,40.729538,2015-02-02 00:10:00+00,2015-02-02 00:03:00+00
4,6444,NaN,NaN,1,1974.0,17362,415,279,276,Subscriber,Pearl St & Hanover Square,Peck Slip & Front St,-74.009260,40.704718,-74.001670,40.707873,2015-02-02 00:09:00+00,2015-02-02 00:04:00+00
5,6445,NaN,NaN,2,1992.0,15475,237,496,420,Subscriber,E 11 St & 2 Ave,E 16 St & 5 Ave,-73.986724,40.730473,-73.992390,40.737262,2015-02-02 00:13:00+00,2015-02-02 00:06:00+00
6,6446,NaN,NaN,1,1968.0,16272,450,477,304,Subscriber,W 49 St & 8 Ave,W 41 St & 8 Ave,-73.987882,40.762272,-73.990026,40.756405,2015-02-02 00:12:00+00,2015-02-02 00:07:00+00
7,6447,NaN,NaN,1,1979.0,16370,391,467,622,Subscriber,Clark St & Henry St,Dean St & 4 Ave,-73.993446,40.697601,-73.978951,40.683125,2015-02-02 00:18:00+00,2015-02-02 00:08:00+00
8,6448,NaN,NaN,1,1963.0,19437,482,434,371,Subscriber,W 15 St & 7 Ave,9 Ave & W 18 St,-73.999318,40.739355,-74.003664,40.743174,2015-02-02 00:15:00+00,2015-02-02 00:09:00+00
9,6449,NaN,NaN,1,1982.0,21211,2008,330,477,Subscriber,Little West St & 1 Pl,Reade St & Broadway,-74.016777,40.705693,-74.005628,40.714505,2015-02-02 00:19:00+00,2015-02-02 00:11:00+00
10,6450,NaN,NaN,2,1978.0,21417,423,521,743,Subscriber,W 54 St & 9 Ave,8 Ave & W 31 St,-73.986905,40.765849,-73.994811,40.750450,2015-02-02 00:25:00+00,2015-02-02 00:12:00+00
11,6451,NaN,NaN,1,1956.0,15722,453,504,599,Subscriber,W 22 St & 8 Ave,1 Ave & E 15 St,-73.999154,40.744751,-73.981656,40.732219,2015-02-02 00:22:00+00,2015-02-02 00:12:00+00
12,6452,NaN,NaN,1,1962.0,18972,236,285,345,Subscriber,St Marks Pl & 2 Ave,Broadway & E 14 St,-73.987140,40.728419,-73.990741,40.734546,2015-02-02 00:18:00+00,2015-02-02 00:12:00+00
13,6453,NaN,NaN,1,1980.0,19628,476,301,721,Subscriber,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-02 00:25:00+00,2015-02-02 00:13:00+00
14,6454,NaN,NaN,1,1978.0,15169,376,279,182,Subscriber,John St & William St,Peck Slip & Front St,-74.007222,40.708621,-74.001670,40.707873,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
15,6455,NaN,NaN,1,1997.0,17533,411,342,154,Subscriber,E 6 St & Avenue D,Columbia St & Rivington St,-73.976687,40.722281,-73.980166,40.717400,2015-02-02 00:16:00+00,2015-02-02 00:13:00+00
16,6456,NaN,NaN,1,1983.0,19761,491,470,435,Subscriber,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-02 00:21:00+00,2015-02-02 00:14:00+00
17,6457,NaN,NaN,1,1993.0,17267,393,236,310,Subscriber,E 5 St & Avenue C,St Marks Pl & 2 Ave,-73.979955,40.722992,-73.987140,40.728419,2015-02-02 00:20:00+00,2015-02-02 00:15:00+00
18,6458,NaN,NaN,1,1964.0,18691,470,470,1274,Subscriber,W 20 St & 8 Ave,W 20 St & 8 Ave,-74.000040,40.743453,-74.000040,40.743453,2015-02-02 00:37:00+00,2015-02-02 00:16:00+00
19,6459,NaN,NaN,1,1977.0,17106,174,485,642,Subscriber,E 25 St & 1 Ave,W 37 St & 5 Ave,-73.977387,40.738177,-73.983390,40.750380,2015-02-02 00:29:00+00,2015-02-02 00:18:00+00
20,6460,NaN,NaN,1,1973.0,20009,483,345,256,Subscriber,E 12 St & 3 Ave,W 13 St & 6 Ave,-73.988900,40.732233,-73.997044,40.736494,2015-02-02 00:22:00+00,2015-02-02 00:18:00+00
21,6461,NaN,NaN,1,1979.0,18777,442,489,334,Subscriber,W 27 St & 7 Ave,10 Ave & W 28 St,-73.993915,40.746647,-74.001768,40.750664,2015-02-02 00:25:00+00,2015-02-02 00:19:00+00
22,6462,NaN,NaN,1,1989.0,15357,174,507,90,Subscriber,E 25 St & 1 Ave,E 25 St & 2 Ave,-73.977387,40.738177,-73.979738,40.739126,2015-02-02 00:20:00+00,2015-02-02 00:19:00+00
23,6463,NaN,NaN,1,1983.0,18487,405,380,203,Subscriber,Washington St & Gansevoort St,W 4 St & 7 Ave S,-74.008119,40.739323,-74.002939,40.734011,2015-02-02 00:23:00+00,2015-02-02 00:20:00+00
24,6464,NaN,NaN,1,1981.0,20863,439,334,649,Subscriber,E 4 St & 2 Ave,W 20 St & 7 Ave,-73.989780,40.726281,-73.997262,40.742388,2015-02-02 00:32:00+00,2015-02-02 00:22:00+00
25,6465,NaN,NaN,1,1970.0,16539,448,508,319,Subscriber,W 37 St & 10 Ave,W 46 St & 11 Ave,-73.997901,40.756604,-73.996674,40.763414,2015-02-02 00:29:00+00,2015-02-02 00:23:00+00
26,6466,NaN,NaN,1,1961.0,18737,301,428,154,Subscriber,E 2 St & Avenue B,E 3 St & 1 Ave,-73.983688,40.722174,-73.987834,40.724677,2015-02-02 00:30:00+00,2015-02-02 00:27:00+00
27,6467,NaN,NaN,2,1980.0,17797,195,331,550,Subscriber,Liberty St & Broadway,Pike St & Monroe St,-74.010434,40.709056,-73.991930,40.711731,2015-02-02 00:37:00+00,2015-02-02 00:28:00+00
28,6468,NaN,NaN,1,1990.0,20638,478,529,268,Subscriber,11 Ave & W 41 St,W 42 St & 8 Ave,-73.998842,40.760301,-73.990985,40.757570,2015-02-02 00:34:00+00,2015-02-02 00:29:00+00
29,6469,NaN,NaN,1,1989.0,17636,366,421,153,Subscriber,Clinton Ave & Myrtle Ave,Clermont Ave & Park Ave,-73.968896,40.693261,-73.971297,40.695734,2015-02-02 00:31:00+00,2015-02-02 00:29:00+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32939,39381,NaN,NaN,1,1957.0,18249,492,465,321,Subscriber,W 33 St & 7 Ave,Broadway & W 41 St,-73.990931,40.750200,-73.986580,40.755136,2015-02-06 23:52:00+00,2015-02-06 23:47:00+00
32940,39382,NaN,NaN,2,1972.0,19146,318,523,449,Subscriber,E 43 St & Vanderbilt Ave,W 38 St & 8 Ave,-73.977987,40.753202,-73.991382,40.754666,2015-02-06 23:55:00+00,2015-02-06 23:48:00+00
32941,39383,NaN,NaN,1,1984.0,15313,434,509,120,Subscriber,9 Ave & W 18 St,9 Ave & W 22 St,-74.003664,40.743174,-74.001971,40.745497,2015-02-06 23:50:00+00,2015-02-06 23:48:00+00
32942,39384,NaN,NaN,1,1979.0,18469,2002,274,977,Subscriber,Wythe Ave & Metropolitan Ave,Lafayette Ave & Fort Greene Pl,-73.963198,40.716887,-73.976682,40.686919,2015-02-07 00:05:00+00,2015-02-06 23:49:00+00
32943,39385,NaN,NaN,1,1966.0,18929,403,402,501,Subscriber,E 2 St & 2 Ave,Broadway & E 22 St,-73.990697,40.725029,-73.989551,40.740343,2015-02-06 23:57:00+00,2015-02-06 23:49:00+00
32944,39386,NaN,NaN,1,1987.0,19009,402,545,441,Subscriber,Broadway & E 22 St,E 23 St & 1 Ave,-73.989551,40.740343,-73.978095,40.736502,2015-02-06 23:58:00+00,2015-02-06 23:50:00+00
32945,39387,NaN,NaN,1,1984.0,17102,438,325,388,Subscriber,St Marks Pl & 1 Ave,E 19 St & 3 Ave,-73.985649,40.727791,-73.984738,40.736245,2015-02-06 23:57:00+00,2015-02-06 23:50:00+00
32946,39388,NaN,NaN,2,1972.0,18686,266,293,607,Subscriber,Avenue D & E 8 St,Lafayette St & E 8 St,-73.975748,40.723684,-73.990765,40.730287,2015-02-07 00:01:00+00,2015-02-06 23:51:00+00
32947,39389,NaN,NaN,1,1989.0,15377,472,402,284,Subscriber,E 32 St & Park Ave,Broadway & E 22 St,-73.981948,40.745712,-73.989551,40.740343,2015-02-06 23:55:00+00,2015-02-06 23:51:00+00
32948,39390,NaN,NaN,1,1984.0,17844,435,383,271,Subscriber,W 21 St & 6 Ave,Greenwich Ave & Charles St,-73.994156,40.741740,-74.000271,40.735238,2015-02-06 23:56:00+00,2015-02-06 23:51:00+00
32949,39391,NaN,NaN,1,1987.0,21040,438,361,572,Subscriber,St Marks Pl & 1 Ave,Allen St & Hester St,-73.985649,40.727791,-73.991908,40.716059,2015-02-07 00:01:00+00,2015-02-06 23:52:00+00
32950,39392,NaN,NaN,1,1981.0,19480,380,503,498,Subscriber,W 4 St & 7 Ave S,E 20 St & Park Ave,-74.002939,40.734011,-73.987520,40.738274,2015-02-07 00:01:00+00,2015-02-06 23:53:00+00
32951,39393,NaN,NaN,1,1978.0,21130,258,324,425,Subscriber,DeKalb Ave & Vanderbilt Ave,DeKalb Ave & Hudson Ave,-73.968855,40.689407,-73.981013,40.689888,2015-02-07 00:00:00+00,2015-02-06 23:53:00+00
32952,39394,NaN,NaN,1,1983.0,16934,435,496,267,Subscriber,W 21 St & 6 Ave,E 16 St & 5 Ave,-73.994156,40.741740,-73.992390,40.737262,2015-02-06 23:58:00+00,2015-02-06 23:53:00+00
32953,39395,NaN,NaN,1,1968.0,20745,318,484,165,Subscriber,E 43 St & Vanderbilt Ave,W 44 St & 5 Ave,-73.977987,40.753202,-73.980144,40.755003,2015-02-06 23:56:00+00,2015-02-06 23:53:00+00
32954,39396,NaN,NaN,1,1969.0,16811,507,464,751,Subscriber,E 25 St & 2 Ave,E 56 St & 3 Ave,-73.979738,40.739126,-73.967597,40.759345,2015-02-07 00:06:00+00,2015-02-06 23:54:00+00
32955,39397,NaN,NaN,1,1980.0,21259,476,301,747,Subscriber,E 31 St & 3 Ave,E 2 St & Avenue B,-73.979661,40.743943,-73.983688,40.722174,2015-02-07 00:07:00+00,2015-02-06 23:54:00+00
32956,39398,NaN,NaN,1,1993.0,15618,375,439,511,Subscriber,Mercer St & Bleecker St,E 4 St & 2 Ave,-73.996951,40.726795,-73.989780,40.726281,2015-02-07 00:03:00+00,2015-02-06 23:54:00+00
32957,39399,NaN,NaN,1,1959.0,17370,486,497,489,Subscriber,Broadway & W 29 St,E 17 St & Broadway,-73.988557,40.746201,-73.990093,40.737050,2015-02-07 00:02:00+00,2015-02-06 23:54:00+00
32958,39400,NaN,NaN,1,1984.0,19430,295,504,1183,Subscriber,Pike St & E Broadway,1 Ave & E 15 St,-73.992939,40.714067,-73.981656,40.732219,2015-02-07 00:14:00+00,2015-02-06 23:55:00+00
32959,39401,NaN,NaN,1,1986.0,18303,512,510,649,Subscriber,W 29 St & 9 Ave,W 51 St & 6 Ave,-73.998393,40.750073,-73.980420,40.760660,2015-02-07 00:06:00+00,2015-02-06 23:55:00+00
32960,39402,NaN,NaN,1,1990.0,20360,453,254,377,Subscriber,W 22 St & 8 Ave,W 11 St & 6 Ave,-73.999154,40.744751,-73.998004,40.735324,2015-02-07 00:01:00+00,2015-02-06 23:55:00+00
32961,39403,NaN,NaN,1,1983.0,21564,491,470,485,Subscriber,E 24 St & Park Ave S,W 20 St & 8 Ave,-73.986022,40.740964,-74.000040,40.743453,2015-02-07 00:04:00+00,2015-02-06 23:56:00+00
32962,39404,NaN,NaN,1,1983.0,21575,368,482,298,Subscriber,Carmine St & 6 Ave,W 15 St & 7 Ave,-74.002150,40.730386,-73.999318,40.739355,2015-02-07 00:01:00+00,2015-02-06 23:56:00+00
32963,39405,NaN,NaN,1,1983.0,21014,346,461,648,Subscriber,Bank St & Hudson St,E 20 St & 2 Ave,-74.006180,40.736529,-73.982050,40.735877,2015-02-07 00:07:00+00,2015-02-06 23:57:00+00
32964,39406,NaN,NaN,2,1989.0,17797,450,252,1261,Subscriber,W 49 St & 8 Ave,MacDougal St & Washington Sq,-73.987882,40.762272,-73.998522,40.732264,2015-02-07 00:19:00+00,2015-02-06 23:58:00+00
32965,39407,NaN,NaN,1,1984.0,16975,270,324,331,Subscriber,Adelphi St & Myrtle Ave,DeKalb Ave & Hudson Ave,-73.971789,40.693083,-73.981013,40.689888,2015-02-07 00:04:00+00,2015-02-06 23:58:00+00
32966,39408,NaN,NaN,1,1982.0,19820,236,345,629,Subscriber,St Marks Pl & 2 Ave,W 13 St & 6 Ave,-73.987140,40.728419,-73.997044,40.736494,2015-02-07 00:10:00+00,2015-02-06 23:59:00+00
32967,39409,NaN,NaN,1,1966.0,19487,502,263,492,Subscriber,Henry St & Grand St,Elizabeth St & Hester St,-73.981346,40.714215,-73.996375,40.717290,2015-02-07 00:07:00+00,2015-02-06 23:59:00+00
32968,39410,NaN,NaN,1,1987.0,15426,301,401,329,Subscriber,E 2 St & Avenue B,Allen St & Rivington St,-73.983688,40.722174,-73.989978,40.720196,2015-02-07 00:04:00+00,2015-02-06 23:59:00+00

In [24]:
test = '''
SELECT AVG(tripduration) AS tripaverage FROM citibike
WHERE extract(ISODOW FROM starttime) not in (6,7)
'''

In [25]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

   tripaverage  Unnamed: 1
0   681.052292         NaN

## Task 3

### Showing the list of start station locations
- Using GROUP BY

In [26]:
test = '''
SELECT CDB_TransformToWebmercator(
       CDB_LatLng(start_station_latitude,start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name FROM citibike
GROUP BY start_station_latitude,start_station_longitude
'''

In [27]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,cartodb_id,start_station_name
0,0101000020110F0000863F88A4096A5FC19D1DAFD5DFF1...,84,Lafayette Ave & Fort Greene Pl
1,0101000020110F0000BB2EC9F82D6A5FC19150E1B461FB...,412,E 43 St & Vanderbilt Ave
2,0101000020110F0000D62721D3CA6D5FC157A5D529F6F5...,516,Greenwich St & Warren St
3,0101000020110F000060197671C96C5FC197A854AF46FA...,359,9 Ave & W 22 St
4,0101000020110F0000993A68067B6C5FC1B222DA492BFA...,78,W 22 St & 8 Ave
5,0101000020110F00004FF9F3E90D6D5FC1F284479FC8F9...,1019,9 Ave & W 16 St
6,0101000020110F00003816CC930D6B5FC17B393D28A0F9...,110,E 24 St & Park Ave S
7,0101000020110F00006B6C9CBF186A5FC109C57CA0D8FC...,7,W 56 St & 6 Ave
8,0101000020110F00008B8D725EB16B5FC1BF41718A0DF6...,460,Allen St & Hester St
9,0101000020110F0000BA97F1D5D36C5FC13D326BC3E4F5...,799,Centre St & Worth St
10,0101000020110F000052716DFB7B6D5FC1634AEE724BF4...,5444,Old Slip & Front St
11,0101000020110F000079B8DA32AB685FC194DBF126F9F4...,459,Bedford Ave & S 9th St
12,0101000020110F000004115CC3E56B5FC1D8A47A41AFF7...,618,Great Jones St
13,0101000020110F00006C38A18AC36A5FC1CCDA8D8DAFFC...,288,Broadway & W 51 St
14,0101000020110F0000EC774642E56C5FC13DF29213A3F7...,26,MacDougal St & Prince St
15,0101000020110F00006EAC10AF716A5FC1491D46B773FC...,519,W 51 St & 6 Ave
16,0101000020110F0000F211F9C1C7695FC1E298B1F0A7F1...,707,S Portland Ave & Hanson Pl
17,0101000020110F00002FE7B4B3FC6D5FC150F152E3E5F5...,1205,Murray St & West St
18,0101000020110F0000C12D0F658D675FC1323CC0ADCAF2...,6,Willoughby Ave & Walworth St
19,0101000020110F00007392D1EEBD685FC17A448F6F1AF2...,8955,Lafayette Ave & St James Pl
20,0101000020110F00003CBD186C2C6A5FC1C2D62BADBCF6...,370,Avenue D & E 3 St
21,0101000020110F0000B8ECD5128D6D5FC1CF0946E36EF6...,797,Harrison St & Hudson St
22,0101000020110F00007BC267B2266C5FC14EDB28B171F2...,153,Henry St & Atlantic Ave
23,0101000020110F0000C74600C9BE6B5FC1451EF62F18F9...,424,E 16 St & 5 Ave
24,0101000020110F0000F9471F1F9A6C5FC125B4B2DACDF8...,55,Greenwich Ave & Charles St
25,0101000020110F0000B4B6D9A8FF695FC1B42BC0556EF1...,3237,Atlantic Ave & Fort Greene Pl
26,0101000020110F00005293059FE96B5FC1283F96AE66FD...,387,W 52 St & 11 Ave
27,0101000020110F0000F9420761D76C5FC19CAEC2F187F6...,1151,Lispenard St & Broadway
28,0101000020110F00001EF7B62F966B5FC1649B856FF3FA...,252,W 33 St & 7 Ave
29,0101000020110F00002011DE6425685FC115AB984DDAF1...,653,Lexington Ave & Classon Ave
...,...,...,...
297,0101000020110F00003A962D08646B5FC1C2CAB91C36F2...,574,State St & Smith St
298,0101000020110F0000BECCC59977685FC1A94F3336D6F2...,968,Emerson Pl & Myrtle Ave
299,0101000020110F00009492832C826A5FC13DFED2D04CF2...,115,DeKalb Ave & Hudson Ave
300,0101000020110F0000CECBC1AD456B5FC149916BC5DDFD...,1386,W 59 St & 10 Ave
301,0101000020110F00002E55C204246D5FC1CA6FCB5F1FFB...,306,11 Ave & W 27 St
302,0101000020110F00005A738F401D6A5FC1E98304C839F9...,218,E 25 St & 1 Ave
303,0101000020110F00000DCC625D696D5FC158A6C354E2F6...,2184,Laight St & Hudson St
304,0101000020110F0000E9C5F392EA6A5FC14849234B6AF3...,805,Concord St & Bridge St
305,0101000020110F000029CC2D4A18685FC1860D5E9389F1...,410,Monroe St & Classon Ave
306,0101000020110F0000B056ADFF5C6A5FC1500051A8DCF1...,533,3 Ave & Schermerhorn St
307,0101000020110F0000416B223CE96B5FC1EE8BEFEA70FA...,411,W 27 St & 7 Ave
308,0101000020110F000049FA5A0D3A695FC1BA4AA87F7AF1...,2402,Fulton St & Clermont Ave
309,0101000020110F000055982AD3F16B5FC1607FD69C04F6...,339,Forsyth St & Canal St
310,0101000020110F0000A452F7AC7B6B5FC185F5C472A5F6...,83,Allen St & Rivington St
311,0101000020110F000001D7D2EC996C5FC1E4C65FCA5FF8...,216,Washington Pl & 6 Ave
312,0101000020110F00003410F605196D5FC18E052E1DD2F8...,1092,Perry St & Bleecker St
313,0101000020110F00006F4EDEDB7D6A5FC177CDA056BEF6...,81,E 2 St & Avenue C
314,0101000020110F00001288289AB06A5FC143D788E4D9FC...,303,Broadway & W 53 St
315,0101000020110F00000AFD8FC8C36C5FC15AF2587A04FB...,176,10 Ave & W 28 St
316,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,W 45 St & 8 Ave
317,0101000020110F0000049C1A69CE6C5FC1205139A81BF8...,13,Carmine St & 6 Ave
318,0101000020110F00002FD56A5DDF685FC1A458A08E56F1...,765,Fulton St & Waverly Ave
319,0101000020110F00002D1B19CE146C5FC11E9608E2CDF3...,1737,Columbia Heights & Cranberry St
320,0101000020110F0000E463F723266A5FC14F49CEE530FB...,2481,Pershing Square North
321,0101000020110F00005E9509B1416B5FC19122492B05FD...,71,W 52 St & 9 Ave
322,0101000020110F000020CE41FA366A5FC1E47EC45CABFA...,491,E 37 St & Lexington Ave
323,0101000020110F000084B804B2CF6A5FC14B886A9682F7...,128,E 7 St & Avenue A
324,0101000020110F0000D13ED956106D5FC18EB95BEE7AFA...,239,W 22 St & 10 Ave
325,0101000020110F00003F37CE288B6C5FC17049FA687DF6...,971,Howard St & Centre St
326,0101000020110F000035628033456B5FC1909E3C7438F6...,1146,Norfolk St & Broome St

### Showing the number of trips started per station

In [28]:
test = '''
SELECT COUNT(tripduration) AS nums,
CDB_TransformToWebmercator(
       CDB_LatLng(start_station_latitude,start_station_longitude)) as the_geom_webmercator,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name FROM citibike
GROUP BY start_station_latitude,start_station_longitude
'''

In [29]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,nums,the_geom_webmercator,cartodb_id,start_station_name
0,54,0101000020110F0000863F88A4096A5FC19D1DAFD5DFF1...,84,Lafayette Ave & Fort Greene Pl
1,486,0101000020110F0000BB2EC9F82D6A5FC19150E1B461FB...,412,E 43 St & Vanderbilt Ave
2,200,0101000020110F0000D62721D3CA6D5FC157A5D529F6F5...,516,Greenwich St & Warren St
3,281,0101000020110F000060197671C96C5FC197A854AF46FA...,359,9 Ave & W 22 St
4,218,0101000020110F0000993A68067B6C5FC1B222DA492BFA...,78,W 22 St & 8 Ave
5,178,0101000020110F00004FF9F3E90D6D5FC1F284479FC8F9...,1019,9 Ave & W 16 St
6,288,0101000020110F00003816CC930D6B5FC17B393D28A0F9...,110,E 24 St & Park Ave S
7,164,0101000020110F00006B6C9CBF186A5FC109C57CA0D8FC...,7,W 56 St & 6 Ave
8,156,0101000020110F00008B8D725EB16B5FC1BF41718A0DF6...,460,Allen St & Hester St
9,82,0101000020110F0000BA97F1D5D36C5FC13D326BC3E4F5...,799,Centre St & Worth St
10,60,0101000020110F000052716DFB7B6D5FC1634AEE724BF4...,5444,Old Slip & Front St
11,13,0101000020110F000079B8DA32AB685FC194DBF126F9F4...,459,Bedford Ave & S 9th St
12,230,0101000020110F000004115CC3E56B5FC1D8A47A41AFF7...,618,Great Jones St
13,200,0101000020110F00006C38A18AC36A5FC1CCDA8D8DAFFC...,288,Broadway & W 51 St
14,247,0101000020110F0000EC774642E56C5FC13DF29213A3F7...,26,MacDougal St & Prince St
15,192,0101000020110F00006EAC10AF716A5FC1491D46B773FC...,519,W 51 St & 6 Ave
16,29,0101000020110F0000F211F9C1C7695FC1E298B1F0A7F1...,707,S Portland Ave & Hanson Pl
17,76,0101000020110F00002FE7B4B3FC6D5FC150F152E3E5F5...,1205,Murray St & West St
18,27,0101000020110F0000C12D0F658D675FC1323CC0ADCAF2...,6,Willoughby Ave & Walworth St
19,32,0101000020110F00007392D1EEBD685FC17A448F6F1AF2...,8955,Lafayette Ave & St James Pl
20,120,0101000020110F00003CBD186C2C6A5FC1C2D62BADBCF6...,370,Avenue D & E 3 St
21,58,0101000020110F0000B8ECD5128D6D5FC1CF0946E36EF6...,797,Harrison St & Hudson St
22,45,0101000020110F00007BC267B2266C5FC14EDB28B171F2...,153,Henry St & Atlantic Ave
23,250,0101000020110F0000C74600C9BE6B5FC1451EF62F18F9...,424,E 16 St & 5 Ave
24,142,0101000020110F0000F9471F1F9A6C5FC125B4B2DACDF8...,55,Greenwich Ave & Charles St
25,36,0101000020110F0000B4B6D9A8FF695FC1B42BC0556EF1...,3237,Atlantic Ave & Fort Greene Pl
26,114,0101000020110F00005293059FE96B5FC1283F96AE66FD...,387,W 52 St & 11 Ave
27,123,0101000020110F0000F9420761D76C5FC19CAEC2F187F6...,1151,Lispenard St & Broadway
28,309,0101000020110F00001EF7B62F966B5FC1649B856FF3FA...,252,W 33 St & 7 Ave
29,17,0101000020110F00002011DE6425685FC115AB984DDAF1...,653,Lexington Ave & Classon Ave
...,...,...,...,...
297,62,0101000020110F00003A962D08646B5FC1C2CAB91C36F2...,574,State St & Smith St
298,30,0101000020110F0000BECCC59977685FC1A94F3336D6F2...,968,Emerson Pl & Myrtle Ave
299,96,0101000020110F00009492832C826A5FC13DFED2D04CF2...,115,DeKalb Ave & Hudson Ave
300,100,0101000020110F0000CECBC1AD456B5FC149916BC5DDFD...,1386,W 59 St & 10 Ave
301,172,0101000020110F00002E55C204246D5FC1CA6FCB5F1FFB...,306,11 Ave & W 27 St
302,209,0101000020110F00005A738F401D6A5FC1E98304C839F9...,218,E 25 St & 1 Ave
303,39,0101000020110F00000DCC625D696D5FC158A6C354E2F6...,2184,Laight St & Hudson St
304,24,0101000020110F0000E9C5F392EA6A5FC14849234B6AF3...,805,Concord St & Bridge St
305,14,0101000020110F000029CC2D4A18685FC1860D5E9389F1...,410,Monroe St & Classon Ave
306,19,0101000020110F0000B056ADFF5C6A5FC1500051A8DCF1...,533,3 Ave & Schermerhorn St
307,320,0101000020110F0000416B223CE96B5FC1EE8BEFEA70FA...,411,W 27 St & 7 Ave
308,27,0101000020110F000049FA5A0D3A695FC1BA4AA87F7AF1...,2402,Fulton St & Clermont Ave
309,110,0101000020110F000055982AD3F16B5FC1607FD69C04F6...,339,Forsyth St & Canal St
310,206,0101000020110F0000A452F7AC7B6B5FC185F5C472A5F6...,83,Allen St & Rivington St
311,113,0101000020110F000001D7D2EC996C5FC1E4C65FCA5FF8...,216,Washington Pl & 6 Ave
312,136,0101000020110F00003410F605196D5FC18E052E1DD2F8...,1092,Perry St & Bleecker St
313,111,0101000020110F00006F4EDEDB7D6A5FC177CDA056BEF6...,81,E 2 St & Avenue C
314,136,0101000020110F00001288289AB06A5FC143D788E4D9FC...,303,Broadway & W 53 St
315,203,0101000020110F00000AFD8FC8C36C5FC15AF2587A04FB...,176,10 Ave & W 28 St
316,141,0101000020110F00001607D538556B5FC119A6CA6F41FC...,124,W 45 St & 8 Ave
317,238,0101000020110F0000049C1A69CE6C5FC1205139A81BF8...,13,Carmine St & 6 Ave
318,55,0101000020110F00002FD56A5DDF685FC1A458A08E56F1...,765,Fulton St & Waverly Ave
319,12,0101000020110F00002D1B19CE146C5FC11E9608E2CDF3...,1737,Columbia Heights & Cranberry St
320,323,0101000020110F0000E463F723266A5FC14F49CEE530FB...,2481,Pershing Square North
321,107,0101000020110F00005E9509B1416B5FC19122492B05FD...,71,W 52 St & 9 Ave
322,138,0101000020110F000020CE41FA366A5FC1E47EC45CABFA...,491,E 37 St & Lexington Ave
323,246,0101000020110F000084B804B2CF6A5FC14B886A9682F7...,128,E 7 St & Avenue A
324,202,0101000020110F0000D13ED956106D5FC18EB95BEE7AFA...,239,W 22 St & 10 Ave
325,124,0101000020110F00003F37CE288B6C5FC17049FA687DF6...,971,Howard St & Centre St
326,83,0101000020110F000035628033456B5FC1909E3C7438F6...,1146,Norfolk St & Broome St

### … but only for stations within 500m of Time Square!
- The coordinates of Time Square is (40.7577,-73.9857)

In [30]:
test = '''
SELECT CDB_TransformToWebmercator(
       CDB_LatLng(start_station_latitude, 
               start_station_longitude)) as the_geom_webmercator,
       COUNT(tripduration) as nums,
       MIN(cartodb_id) as cartodb_id,
       MIN(start_station_name) as start_station_name FROM citibike
       WHERE ST_DWithin(CDB_LatLng(start_station_latitude,
                                start_station_longitude)::geography,
                     CDB_LatLng(40.7577, -73.9857)::geography,
                     500)
GROUP BY start_station_latitude,start_station_longitude
'''

In [31]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,nums,cartodb_id,start_station_name
0,0101000020110F0000F22A632FBE6A5FC1363A28CFADFB...,112,1115,W 43 St & 6 Ave
1,0101000020110F000004AF971C1D6B5FC17A48F3C1A8FB...,251,54,Broadway & W 41 St
2,0101000020110F00001607D538556B5FC119A6CA6F41FC...,141,124,W 45 St & 8 Ave
3,0101000020110F00003F9300B2976B5FC1B8B88F3102FC...,221,783,W 42 St & 8 Ave
4,0101000020110F0000F55695027D6B5FC186E5BB69D7FB...,507,33,W 41 St & 8 Ave
5,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,213,42,Broadway & W 49 St
6,0101000020110F00009BB87D02B76A5FC146C144E9E5FB...,141,19,W 45 St & 6 Ave

## Task 4

### Find the station that had the longest average trip duration during weekends and within 500m of TimeSquare!

In [32]:
test = '''
SELECT CDB_TransformToWebmercator(
       CDB_LatLng(start_station_latitude,
                  start_station_longitude)) as the_geom_webmercator,
                  COUNT(tripduration) as nums,
                  AVG(tripduration) as tripaverage,
                  MIN(cartodb_id) as cartodb_id,
                  MIN(start_station_id) as start_station_id,
                  MIN(start_station_name) as start_station_name FROM citibike
       WHERE ST_DWithin(CDB_LatLng(start_station_latitude,
                                start_station_longitude)::geography,
                     CDB_LatLng(40.7577, -73.9857)::geography,
                     500)
       AND extract(ISODOW FROM starttime) in (6,7)
GROUP BY start_station_id,start_station_latitude,start_station_longitude
ORDER BY tripaverage DESC
LIMIT 1
'''

In [33]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

,the_geom_webmercator,nums,tripaverage,cartodb_id,start_station_id,start_station_name
0,0101000020110F000020D6742CE16A5FC112F4D73D73FC...,48,1010.104167,42,173,Broadway & W 49 St

### Extra: create lines for trips started from stations within 500m of Times Squares and lasted less than 2 hours. The number of trips per each pair of stations are output as attributes of these lines.

In [34]:
test = '''
SELECT ST_Makeline(
     CDB_TransformToWebmercator(
        CDB_LatLng(start_station_latitude,
                   start_station_longitude)),
     CDB_TransformToWebmercator(
        CDB_LatLng(end_station_latitude,
                   end_station_longitude))  
  ) as the_geom_webmercator,
        MIN(cartodb_id) as cartodb_id,
        COUNT(tripduration) as nums FROM citibike
WHERE ST_DWithin(CDB_LatLng(start_station_latitude,
                   start_station_longitude)::geography,
                 CDB_LatLng(40.7577, -73.9857)::geography,
                 500)
AND tripduration < 7200
GROUP BY start_station_id,
start_station_latitude,start_station_longitude,end_station_id,end_station_latitude, end_station_longitude
'''

In [35]:
pd.read_csv(StringIO.StringIO(queryCartoDB(test)), sep=',')

                                  the_geom_webmercator  cartodb_id  nums
0    0102000020110F00000200000020D6742CE16A5FC112F4...       18466     2
1    0102000020110F000002000000F55695027D6B5FC186E5...        2226     2
2    0102000020110F00000200000004AF971C1D6B5FC17A48...       15621     2
3    0102000020110F0000020000009BB87D02B76A5FC146C1...       34734     1
4    0102000020110F000002000000F22A632FBE6A5FC1363A...       37006     1
5    0102000020110F00000200000004AF971C1D6B5FC17A48...        6007     3
6    0102000020110F000002000000F22A632FBE6A5FC1363A...       20272     4
7    0102000020110F0000020000001607D538556B5FC119A6...       11540     3
8    0102000020110F0000020000009BB87D02B76A5FC146C1...       13614     3
9    0102000020110F000002000000F55695027D6B5FC186E5...       39800     1
10   0102000020110F00000200000004AF971C1D6B5FC17A48...       29033     1
11   0102000020110F00000200000020D6742CE16A5FC112F4...       45442     1
12   0102000020110F0000020000009BB87D02B76A5FC146C1...       14181     2
13   0102000020110F0000020000001607D538556B5FC119A6...         959     4
14   0102000020110F0000020000003F9300B2976B5FC1B8B8...        7889     2
15   0102000020110F0000020000009BB87D02B76A5FC146C1...        7076    12
16   0102000020110F0000020000001607D538556B5FC119A6...       33533     1
17   0102000020110F00000200000004AF971C1D6B5FC17A48...       34712     1
18   0102000020110F0000020000003F9300B2976B5FC1B8B8...       13230     5
19   0102000020110F000002000000F55695027D6B5FC186E5...        4507     2
20   0102000020110F000002000000F55695027D6B5FC186E5...       13031    31
21   0102000020110F000002000000F22A632FBE6A5FC1363A...       17712     1
22   0102000020110F0000020000009BB87D02B76A5FC146C1...       34501     1
23   0102000020110F000002000000F55695027D6B5FC186E5...        9844     2
24   0102000020110F000002000000F55695027D6B5FC186E5...         356     5
25   0102000020110F00000200000004AF971C1D6B5FC17A48...       10223     5
26   0102000020110F000002000000F55695027D6B5FC186E5...       25199     2
27   0102000020110F0000020000001607D538556B5FC119A6...        2536     2
28   0102000020110F000002000000F55695027D6B5FC186E5...       37521     1
29   0102000020110F000002000000F55695027D6B5FC186E5...       19530     4
..                                                 ...         ...   ...
542  0102000020110F0000020000003F9300B2976B5FC1B8B8...       22083     3
543  0102000020110F00000200000020D6742CE16A5FC112F4...       34099     2
544  0102000020110F00000200000020D6742CE16A5FC112F4...        7354     1
545  0102000020110F0000020000009BB87D02B76A5FC146C1...       16753     4
546  0102000020110F00000200000020D6742CE16A5FC112F4...       21315     1
547  0102000020110F000002000000F22A632FBE6A5FC1363A...       38470     1
548  0102000020110F000002000000F55695027D6B5FC186E5...       30699     1
549  0102000020110F00000200000004AF971C1D6B5FC17A48...       12092     3
550  0102000020110F0000020000009BB87D02B76A5FC146C1...       12625     1
551  0102000020110F0000020000001607D538556B5FC119A6...       22819     1
552  0102000020110F00000200000004AF971C1D6B5FC17A48...        8767     3
553  0102000020110F0000020000009BB87D02B76A5FC146C1...       14978     3
554  0102000020110F00000200000004AF971C1D6B5FC17A48...        7686     6
555  0102000020110F0000020000003F9300B2976B5FC1B8B8...        6699     1
556  0102000020110F000002000000F55695027D6B5FC186E5...       17638     1
557  0102000020110F000002000000F22A632FBE6A5FC1363A...       28510     2
558  0102000020110F0000020000009BB87D02B76A5FC146C1...       17023     1
559  0102000020110F0000020000009BB87D02B76A5FC146C1...        3105     6
560  0102000020110F00000200000020D6742CE16A5FC112F4...       13485     4
561  0102000020110F000002000000F55695027D6B5FC186E5...       13694     3
562  0102000020110F000002000000F55695027D6B5FC186E5...        2329     8
563  0102000020110F0000020000003F9300B2976B5FC1B8B8...        5582     2
564  0102000020110F000002000000F55695027D6B5FC186E5...       12873     3
565  0102000020110F000002000000F22A632FBE6A5FC1363A...       17983     2
566  0102000020110F0000020000001607D538556B5FC119A6...       22345     1
567  0102000020110F00000200000020D6742CE16A5FC112F4...       27219     2
568  0102000020110F0000020000001607D538556B5FC119A6...        7341    10
569  0102000020110F0000020000003F9300B2976B5FC1B8B8...        8971     1
570  0102000020110F000002000000F22A632FBE6A5FC1363A...       36545     1
571  0102000020110F00000200000004AF971C1D6B5FC17A48...       18854     1

[572 rows x 3 columns]

# extra credit: make the function python 2 and 3 compatible so that it works on the  PUI2016_Python3 kernel